#!/usr/bin/env bash
set -euo pipefail

# ======================================================================
# AUTO-GENERATED by scripts/pack_generate_dockerfile.sh
# Do not edit directly. Edit src/scripts/*.sh and re-pack.
# ======================================================================

# Stage extract_munitor_vars.sh to /tmp/munitor/
mkdir -p /tmp/munitor

cat > /tmp/munitor/munitor_helpers.sh << 'MUNITOR_HELPERS_EOF'
#!/usr/bin/env bash
# Shared helper library for Munitor orb scripts.
# Source this at the top of each script for consistent diagnostics.
#
# Sourcing pattern (works even if helpers are missing):
#   MUNITOR_HELPERS="${MUNITOR_HELPERS:-$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)/munitor_helpers.sh}"
#   [[ -f "${MUNITOR_HELPERS}" ]] && source "${MUNITOR_HELPERS}"

# Guard against double-sourcing
[[ -n "${_MUNITOR_HELPERS_LOADED:-}" ]] && return 0
_MUNITOR_HELPERS_LOADED=1

# --------------------------------------------------------------------------
# munitor_header <step_name>
#
# Print a standard banner with date, hostname, and working directory.
# --------------------------------------------------------------------------
munitor_header() {
  local name="${1:-unknown}"
  echo "========================================"
  echo "  Munitor: ${name}"
  echo "  Date:  $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
  echo "  Host:  $(hostname 2>/dev/null || echo 'unknown')"
  echo "  Dir:   $(pwd)"
  echo "========================================"
}

# --------------------------------------------------------------------------
# munitor_check_tool <command> [version_flag]
#
# Verify a tool is in PATH and print its version.  Exits 1 with a clear
# message if the tool is missing.
# --------------------------------------------------------------------------
munitor_check_tool() {
  local cmd="$1"
  local version_flag="${2:---version}"

  if ! command -v "${cmd}" &>/dev/null; then
    echo "ERROR: Required tool '${cmd}' is not installed or not in PATH."
    echo "  PATH: ${PATH}"
    exit 1
  fi

  local ver
  ver=$("${cmd}" "${version_flag}" 2>&1 | head -1) || true
  echo "  ${cmd}: ${ver}"
}

# --------------------------------------------------------------------------
# munitor_download_with_retry <url> <output> [retries] [delay]
#
# Download a URL with retry logic. Tries curl first, falls back to wget.
# --------------------------------------------------------------------------
munitor_download_with_retry() {
  local url="$1"
  local output="$2"
  local retries="${3:-3}"
  local delay="${4:-5}"

  for attempt in $(seq 1 "${retries}"); do
    if command -v curl &>/dev/null; then
      if curl -fsSL --retry 2 "${url}" -o "${output}"; then
        return 0
      fi
    elif command -v wget &>/dev/null; then
      if wget -q "${url}" -O "${output}"; then
        return 0
      fi
    else
      echo "ERROR: Neither curl nor wget is available."
      exit 1
    fi

    if [[ "${attempt}" -lt "${retries}" ]]; then
      echo "  Download failed (attempt ${attempt}/${retries}), retrying in ${delay}s..."
      sleep "${delay}"
    fi
  done

  echo "ERROR: Failed to download ${url} after ${retries} attempts."
  return 1
}
MUNITOR_HELPERS_EOF

cat > /tmp/munitor/extract_munitor_vars.sh << 'MUNITOR_EXTRACT_EOF'
#!/usr/bin/env bash
# Shared helper for extracting variables from .munitor.yml
# Source this file to get MUNITOR_* variables exported

set -euo pipefail

extract_munitor_vars() {
  local config_file="${1:-.munitor.yml}"

  if [[ ! -f "${config_file}" ]]; then
    echo "ERROR: Config file '${config_file}' not found." >&2
    return 1
  fi

  # --- Org defaults (change this block when forking for another org) ---
  local ORG_DOCKER_REGISTRY="ghcr.io/KofTwentyTwo"
  local ORG_NPM_SCOPE="@koftwentytwo"
  local ORG_CI_EMAIL="munitor-ci@koftwentytwo.com"
  local ORG_CI_NAME="Munitor CI"
  local ORG_ORB_SLUG="kof22/munitor"

  # Core pipeline settings
  MUNITOR_PIPELINE=$(yq '.pipeline' "${config_file}")
  MUNITOR_ORB_VERSION=$(yq '.orb_version // ""' "${config_file}")
  MUNITOR_IMAGE_NAME=$(yq '.image_name // ""' "${config_file}")
  MUNITOR_JAVA_VERSION=$(yq '.java_version // "21"' "${config_file}")
  MUNITOR_NODE_VERSION=$(yq '.node_version // "20"' "${config_file}")
  MUNITOR_SONAR_PROJECT_KEY=$(yq '.sonar.project_key // ""' "${config_file}")
  MUNITOR_DOCKER_REGISTRY=$(yq '.docker.registry // ""' "${config_file}")
  if [[ -z "${MUNITOR_DOCKER_REGISTRY}" || "${MUNITOR_DOCKER_REGISTRY}" == "null" ]]; then
    MUNITOR_DOCKER_REGISTRY="${ORG_DOCKER_REGISTRY}"
  fi
  MUNITOR_CD_REPO=$(yq '.cd.repo // ""' "${config_file}")
  MUNITOR_CD_FORMAT=$(yq '.cd.format // "helm"' "${config_file}")
  MUNITOR_CD_ENV_DEVELOP=$(yq '.cd.env.develop // "develop"' "${config_file}")
  MUNITOR_CD_ENV_STAGING=$(yq '.cd.env.staging // "staging"' "${config_file}")
  MUNITOR_CD_ENV_PROD=$(yq '.cd.env.prod // "prod"' "${config_file}")
  MUNITOR_CD_ENV_RELEASE=$(yq '.cd.env.release // "staging"' "${config_file}")
  MUNITOR_COVERAGE_MIN=$(yq '.coverage.min_instruction // "70"' "${config_file}")
  MUNITOR_E2E=$(yq '.e2e // false' "${config_file}")
  MUNITOR_SBOM=$(yq '.sbom // false' "${config_file}")

  # Contexts
  MUNITOR_CONTEXT_REGISTRY=$(yq '.contexts.registry // ""' "${config_file}")
  MUNITOR_CONTEXT_GITHUB=$(yq '.contexts.github // ""' "${config_file}")
  MUNITOR_CONTEXT_SONAR=$(yq '.contexts.sonar // ""' "${config_file}")
  MUNITOR_CONTEXT_NVD=$(yq '.contexts.nvd // ""' "${config_file}")

  # GitHub Release: auto-enabled when contexts.github is present
  if [[ -n "${MUNITOR_CONTEXT_GITHUB}" ]]; then
    MUNITOR_GITHUB_RELEASE="true"
  else
    MUNITOR_GITHUB_RELEASE="false"
  fi

  # Node-api extended features
  MUNITOR_NPM_AUTH=$(yq '.npm.private_registry // false' "${config_file}")
  MUNITOR_NPM_SCOPES=$(yq -o=json -I=0 '.npm.scopes // []' "${config_file}")
  MUNITOR_SERVICES_JSON=$(yq '.services // [] | tojson' "${config_file}")
  if [[ "${MUNITOR_SERVICES_JSON}" == "[]" ]]; then
    MUNITOR_SERVICES="false"
  else
    MUNITOR_SERVICES="true"
  fi
  MUNITOR_TEST_SETUP_SCRIPT=$(yq '.test.setup // ""' "${config_file}")
  if [[ -n "${MUNITOR_TEST_SETUP_SCRIPT}" ]]; then
    MUNITOR_TEST_SETUP="true"
  else
    MUNITOR_TEST_SETUP="false"
  fi
  MUNITOR_TEST_COMMANDS_JSON=$(yq '.test.commands // [] | tojson' "${config_file}")
  if [[ "${MUNITOR_TEST_COMMANDS_JSON}" == "[]" ]]; then
    MUNITOR_CUSTOM_TEST="false"
  else
    MUNITOR_CUSTOM_TEST="true"
  fi
  MUNITOR_COVERAGE_TOOL=$(yq '.test.coverage.tool // "jest"' "${config_file}")
  MUNITOR_COVERAGE_COMMAND=$(yq '.test.coverage.command // ""' "${config_file}")
  if [[ -n "${MUNITOR_COVERAGE_COMMAND}" ]]; then
    MUNITOR_COVERAGE_CMD="true"
  else
    MUNITOR_COVERAGE_CMD="false"
  fi
  # Allow test.coverage.min_instruction to override coverage.min_instruction
  MUNITOR_TEST_COVERAGE_MIN=$(yq '.test.coverage.min_instruction // ""' "${config_file}")
  if [[ -n "${MUNITOR_TEST_COVERAGE_MIN}" ]]; then
    MUNITOR_COVERAGE_MIN="${MUNITOR_TEST_COVERAGE_MIN}"
  fi

  # Terraform pipeline settings
  MUNITOR_TF_PATH=$(yq '.terraform.path // "terraform/"' "${config_file}")
  MUNITOR_TF_LIVE_PATH=$(yq '.terraform.live_path // "terraform/live"' "${config_file}")
  MUNITOR_TF_ENVIRONMENTS=$(yq '.terraform.environments // ["production"] | join(" ")' "${config_file}")
  MUNITOR_CHECKOV_SKIP=$(yq '.terraform.checkov_skip // ""' "${config_file}")
  # Kustomize / CD repo validation settings
  MUNITOR_KUSTOMIZE_VERSION=$(yq '.kustomize.version // "5.5.0"' "${config_file}")
  MUNITOR_KUSTOMIZE_BASE_PATH=$(yq '.kustomize.base_path // "base/"' "${config_file}")
  MUNITOR_KUSTOMIZE_LOAD_RESTRICTOR=$(yq '.kustomize.load_restrictor // "true"' "${config_file}")
  MUNITOR_KUSTOMIZE_SCAN_OVERLAY=$(yq '.kustomize.scan_overlay // "production"' "${config_file}")
  MUNITOR_KUSTOMIZE_OVERLAYS=$(yq '.kustomize.overlays // [] | join(" ")' "${config_file}")
  MUNITOR_KUBE_LINTER_CONFIG=$(yq '.kube_linter_config // ""' "${config_file}")
  MUNITOR_YAMLLINT_PATHS="base/ overlays/ argocd-apps/"

  # SAST: supports boolean (true/false) or object form (sast: { fail_on_findings: false })
  local sast_raw
  sast_raw=$(yq '.sast' "${config_file}")
  case "${sast_raw}" in
    true)
      MUNITOR_SAST="true"
      MUNITOR_SAST_FAIL_ON_FINDINGS="true"
      ;;
    false|null)
      MUNITOR_SAST="false"
      MUNITOR_SAST_FAIL_ON_FINDINGS="true"
      ;;
    *)
      # Object form: sast is present as a map, so SAST is enabled
      MUNITOR_SAST="true"
      local fof
      fof=$(yq '.sast.fail_on_findings' "${config_file}")
      if [[ "${fof}" == "false" ]]; then
        MUNITOR_SAST_FAIL_ON_FINDINGS="false"
      else
        MUNITOR_SAST_FAIL_ON_FINDINGS="true"
      fi
      ;;
  esac

  # Node framework (nextjs or express)
  MUNITOR_NODE_FRAMEWORK=$(yq '.node.framework // "nextjs"' "${config_file}")

  # Org-level variables (derived from defaults block)
  MUNITOR_CI_EMAIL="${ORG_CI_EMAIL}"
  MUNITOR_CI_NAME="${ORG_CI_NAME}"
  MUNITOR_NPM_DEFAULT_SCOPE="${ORG_NPM_SCOPE}"
  MUNITOR_ORB_SLUG="${ORG_ORB_SLUG}"

  # Health check settings
  MUNITOR_HEALTH_PATH=$(yq '.health.path // "/api/health"' "${config_file}")
  MUNITOR_HEALTH_PORT=$(yq '.health.port // ""' "${config_file}")
  if [[ -z "${MUNITOR_HEALTH_PORT}" || "${MUNITOR_HEALTH_PORT}" == "null" ]]; then
    case "${MUNITOR_PIPELINE}" in
      node-api) MUNITOR_HEALTH_PORT="3000" ;;
      *) MUNITOR_HEALTH_PORT="8080" ;;
    esac
  fi
  MUNITOR_HEALTH_DB=$(yq '.health.db // false' "${config_file}")

  # Derived flags
  if [[ -n "${MUNITOR_SONAR_PROJECT_KEY}" ]]; then
    MUNITOR_SONAR="true"
  else
    MUNITOR_SONAR="false"
  fi

  if [[ -n "${MUNITOR_CD_REPO}" ]]; then
    MUNITOR_CD="true"
  else
    MUNITOR_CD="false"
  fi

  # Export all variables
  export MUNITOR_PIPELINE MUNITOR_ORB_VERSION MUNITOR_IMAGE_NAME MUNITOR_JAVA_VERSION MUNITOR_NODE_VERSION
  export MUNITOR_SONAR_PROJECT_KEY MUNITOR_DOCKER_REGISTRY MUNITOR_CD_REPO MUNITOR_CD_FORMAT
  export MUNITOR_CD_ENV_DEVELOP MUNITOR_CD_ENV_STAGING MUNITOR_CD_ENV_PROD MUNITOR_CD_ENV_RELEASE
  export MUNITOR_COVERAGE_MIN MUNITOR_E2E MUNITOR_SBOM
  export MUNITOR_CONTEXT_REGISTRY MUNITOR_CONTEXT_GITHUB MUNITOR_CONTEXT_SONAR MUNITOR_CONTEXT_NVD
  export MUNITOR_GITHUB_RELEASE
  export MUNITOR_NPM_AUTH MUNITOR_NPM_SCOPES
  export MUNITOR_SERVICES MUNITOR_SERVICES_JSON
  export MUNITOR_TEST_SETUP MUNITOR_TEST_SETUP_SCRIPT
  export MUNITOR_CUSTOM_TEST MUNITOR_TEST_COMMANDS_JSON
  export MUNITOR_COVERAGE_TOOL MUNITOR_COVERAGE_CMD MUNITOR_COVERAGE_COMMAND
  export MUNITOR_TF_PATH MUNITOR_TF_LIVE_PATH MUNITOR_TF_ENVIRONMENTS MUNITOR_CHECKOV_SKIP MUNITOR_SAST MUNITOR_SAST_FAIL_ON_FINDINGS
  export MUNITOR_KUSTOMIZE_VERSION MUNITOR_KUSTOMIZE_BASE_PATH MUNITOR_KUSTOMIZE_LOAD_RESTRICTOR
  export MUNITOR_KUSTOMIZE_SCAN_OVERLAY MUNITOR_KUSTOMIZE_OVERLAYS MUNITOR_KUBE_LINTER_CONFIG MUNITOR_YAMLLINT_PATHS
  export MUNITOR_NODE_FRAMEWORK
  export MUNITOR_CI_EMAIL MUNITOR_CI_NAME MUNITOR_NPM_DEFAULT_SCOPE MUNITOR_ORB_SLUG
  export MUNITOR_HEALTH_PATH MUNITOR_HEALTH_PORT MUNITOR_HEALTH_DB
  export MUNITOR_SONAR MUNITOR_CD
}

# Build the envsubst variable list
get_envsubst_vars() {
  # shellcheck disable=SC2016
  echo '${MUNITOR_PIPELINE} ${MUNITOR_ORB_VERSION} ${MUNITOR_IMAGE_NAME} ${MUNITOR_JAVA_VERSION} ${MUNITOR_NODE_VERSION} ${MUNITOR_SONAR_PROJECT_KEY} ${MUNITOR_DOCKER_REGISTRY} ${MUNITOR_CD_REPO} ${MUNITOR_CD_FORMAT} ${MUNITOR_CD_ENV_DEVELOP} ${MUNITOR_CD_ENV_STAGING} ${MUNITOR_CD_ENV_PROD} ${MUNITOR_CD_ENV_RELEASE} ${MUNITOR_COVERAGE_MIN} ${MUNITOR_E2E} ${MUNITOR_SBOM} ${MUNITOR_CONTEXT_REGISTRY} ${MUNITOR_CONTEXT_GITHUB} ${MUNITOR_CONTEXT_SONAR} ${MUNITOR_CONTEXT_NVD} ${MUNITOR_NPM_AUTH} ${MUNITOR_NPM_SCOPES} ${MUNITOR_SERVICES_JSON} ${MUNITOR_TEST_SETUP_SCRIPT} ${MUNITOR_TEST_COMMANDS_JSON} ${MUNITOR_COVERAGE_TOOL} ${MUNITOR_COVERAGE_COMMAND} ${MUNITOR_GITHUB_RELEASE} ${MUNITOR_SAST} ${MUNITOR_SAST_FAIL_ON_FINDINGS} ${MUNITOR_HEALTH_PATH} ${MUNITOR_HEALTH_PORT} ${MUNITOR_HEALTH_DB} ${MUNITOR_TF_PATH} ${MUNITOR_TF_LIVE_PATH} ${MUNITOR_TF_ENVIRONMENTS} ${MUNITOR_CHECKOV_SKIP} ${MUNITOR_KUSTOMIZE_VERSION} ${MUNITOR_KUSTOMIZE_BASE_PATH} ${MUNITOR_KUSTOMIZE_LOAD_RESTRICTOR} ${MUNITOR_KUSTOMIZE_SCAN_OVERLAY} ${MUNITOR_KUSTOMIZE_OVERLAYS} ${MUNITOR_KUBE_LINTER_CONFIG} ${MUNITOR_YAMLLINT_PATHS} ${MUNITOR_CI_EMAIL} ${MUNITOR_CI_NAME} ${MUNITOR_NPM_DEFAULT_SCOPE} ${MUNITOR_ORB_SLUG}'
}
MUNITOR_EXTRACT_EOF

# ======================================================================
# Main generate_dockerfile.sh logic
# ======================================================================

set -euo pipefail

CONFIG_FILE="${MUNITOR_CONFIG:-.munitor.yml}"

# When run via CircleCI << include() >>, BASH_SOURCE is empty.
# Fall back to MUNITOR_SCRIPT_DIR set by the command YAML.
if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
else
  SCRIPT_DIR="${MUNITOR_SCRIPT_DIR:-/tmp/munitor}"
fi

# Source shared helpers
MUNITOR_HELPERS="${MUNITOR_HELPERS:-${SCRIPT_DIR}/munitor_helpers.sh}"
# shellcheck source=munitor_helpers.sh
if [[ -f "${MUNITOR_HELPERS}" ]]; then source "${MUNITOR_HELPERS}"
elif ! type munitor_header &>/dev/null; then
  munitor_header() { echo "=== Munitor: ${1:-unknown} ==="; }
  munitor_check_tool() { command -v "$1" &>/dev/null || { echo "ERROR: $1 not found"; exit 1; }; }
  munitor_download_with_retry() { curl -fsSL --retry 3 "$1" -o "$2"; }
fi

munitor_header "generate_dockerfile"
munitor_check_tool yq --version

if [[ ! -f "${CONFIG_FILE}" ]]; then
  echo "ERROR: ${CONFIG_FILE} not found in workspace." >&2
  exit 1
fi

# Source shared variable extraction
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/extract_munitor_vars.sh"
extract_munitor_vars "${CONFIG_FILE}"

case "${MUNITOR_PIPELINE}" in
  node-api)
    echo "Generating Dockerfile for node-api (node ${MUNITOR_NODE_VERSION}, framework ${MUNITOR_NODE_FRAMEWORK})"

    case "${MUNITOR_NODE_FRAMEWORK}" in
      nextjs)
        # Multi-stage Next.js standalone Dockerfile.
        # Assumes `output: 'standalone'` in next.config.js.
        cat > Dockerfile <<DOCKERFILE
FROM node:${MUNITOR_NODE_VERSION}-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:${MUNITOR_NODE_VERSION}-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV STANDALONE=true
RUN npm run build

FROM node:${MUNITOR_NODE_VERSION}-alpine AS runner
WORKDIR /app
RUN apk update && apk upgrade --no-cache && rm -rf /var/cache/apk/*
# Remove npm/npx and their bundled deps (glob, tar) to reduce attack surface.
# The runner only needs the node binary to execute server.js.
RUN npm cache clean --force && rm -rf /usr/local/lib/node_modules /usr/local/bin/npm /usr/local/bin/npx
RUN addgroup --system --gid 1001 nodejs \\
 && adduser --system --uid 1001 nextjs
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
ENV PORT=3000
CMD ["node", "server.js"]
DOCKERFILE
        ;;

      express)
        # Two-stage Express Dockerfile. Uses package.json "main" field via `node .`.
        cat > Dockerfile <<DOCKERFILE
FROM node:${MUNITOR_NODE_VERSION}-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev

FROM node:${MUNITOR_NODE_VERSION}-alpine AS runner
WORKDIR /app
RUN apk update && apk upgrade --no-cache && rm -rf /var/cache/apk/*
RUN npm cache clean --force && rm -rf /usr/local/lib/node_modules /usr/local/bin/npm /usr/local/bin/npx
RUN addgroup --system --gid 1001 nodejs \\
 && adduser --system --uid 1001 appuser -G nodejs
COPY --from=deps /app/node_modules ./node_modules
COPY . .
USER appuser
EXPOSE ${MUNITOR_HEALTH_PORT}
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \\
    CMD wget --no-verbose --tries=1 --spider http://localhost:${MUNITOR_HEALTH_PORT}${MUNITOR_HEALTH_PATH} || exit 1
CMD ["node", "."]
DOCKERFILE
        ;;

      *)
        echo "ERROR: Unsupported node framework '${MUNITOR_NODE_FRAMEWORK}'. Use 'nextjs' or 'express'." >&2
        exit 1
        ;;
    esac
    ;;

  java-webapp)
    echo "Generating Dockerfile for java-webapp (java ${MUNITOR_JAVA_VERSION})"

    # Find the primary application JAR (exclude original-*, sources, javadoc)
    APP_JAR=$(find target -maxdepth 1 -name "*.jar" \
      ! -name "original-*" ! -name "*-sources.jar" ! -name "*-javadoc.jar" \
      2>/dev/null | head -1) || true

    if [[ -z "${APP_JAR}" ]]; then
      echo "ERROR: No application JAR found in target/" >&2
      exit 1
    fi

    echo "Using JAR: ${APP_JAR}"

    cat > Dockerfile <<DOCKERFILE
FROM eclipse-temurin:${MUNITOR_JAVA_VERSION}-jre-alpine

RUN apk update && apk upgrade --no-cache

RUN addgroup -g 1001 -S appgroup && \\
    adduser -u 1001 -S appuser -G appgroup

WORKDIR /app

COPY ${APP_JAR} app.jar

RUN chown -R appuser:appgroup /app

USER appuser

ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError"

EXPOSE ${MUNITOR_HEALTH_PORT}

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \\
    CMD wget --no-verbose --tries=1 --spider http://localhost:${MUNITOR_HEALTH_PORT}${MUNITOR_HEALTH_PATH} || exit 1

ENTRYPOINT ["sh", "-c", "java \$JAVA_OPTS -jar app.jar"]
DOCKERFILE
    ;;

  *)
    echo "ERROR: Unsupported pipeline type '${MUNITOR_PIPELINE}' for Dockerfile generation." >&2
    exit 1
    ;;
esac

echo "Dockerfile generated successfully."
