#!/usr/bin/env bash
set -euo pipefail

# ======================================================================
# AUTO-GENERATED by scripts/pack_generate_config.sh
# Do not edit directly. Edit src/scripts/*.sh and re-pack.
# ======================================================================

# Stage helper files to /tmp/munitor/ so generate_config.sh can find them
mkdir -p /tmp/munitor/templates/partials

cat > /tmp/munitor/munitor_helpers.sh << 'MUNITOR_HELPERS_EOF'
#!/usr/bin/env bash
# Shared helper library for Munitor orb scripts.
# Source this at the top of each script for consistent diagnostics.
#
# Sourcing pattern (works even if helpers are missing):
#   MUNITOR_HELPERS="${MUNITOR_HELPERS:-$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)/munitor_helpers.sh}"
#   [[ -f "${MUNITOR_HELPERS}" ]] && source "${MUNITOR_HELPERS}"

# Guard against double-sourcing
[[ -n "${_MUNITOR_HELPERS_LOADED:-}" ]] && return 0
_MUNITOR_HELPERS_LOADED=1

# --------------------------------------------------------------------------
# munitor_header <step_name>
#
# Print a standard banner with date, hostname, and working directory.
# --------------------------------------------------------------------------
munitor_header() {
  local name="${1:-unknown}"
  echo "========================================"
  echo "  Munitor: ${name}"
  echo "  Date:  $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
  echo "  Host:  $(hostname 2>/dev/null || echo 'unknown')"
  echo "  Dir:   $(pwd)"
  echo "========================================"
}

# --------------------------------------------------------------------------
# munitor_check_tool <command> [version_flag]
#
# Verify a tool is in PATH and print its version.  Exits 1 with a clear
# message if the tool is missing.
# --------------------------------------------------------------------------
munitor_check_tool() {
  local cmd="$1"
  local version_flag="${2:---version}"

  if ! command -v "${cmd}" &>/dev/null; then
    echo "ERROR: Required tool '${cmd}' is not installed or not in PATH."
    echo "  PATH: ${PATH}"
    exit 1
  fi

  local ver
  ver=$("${cmd}" "${version_flag}" 2>&1 | head -1) || true
  echo "  ${cmd}: ${ver}"
}

# --------------------------------------------------------------------------
# munitor_download_with_retry <url> <output> [retries] [delay]
#
# Download a URL with retry logic. Tries curl first, falls back to wget.
# --------------------------------------------------------------------------
munitor_download_with_retry() {
  local url="$1"
  local output="$2"
  local retries="${3:-3}"
  local delay="${4:-5}"

  for attempt in $(seq 1 "${retries}"); do
    if command -v curl &>/dev/null; then
      if curl -fsSL --retry 2 "${url}" -o "${output}"; then
        return 0
      fi
    elif command -v wget &>/dev/null; then
      if wget -q "${url}" -O "${output}"; then
        return 0
      fi
    else
      echo "ERROR: Neither curl nor wget is available."
      exit 1
    fi

    if [[ "${attempt}" -lt "${retries}" ]]; then
      echo "  Download failed (attempt ${attempt}/${retries}), retrying in ${delay}s..."
      sleep "${delay}"
    fi
  done

  echo "ERROR: Failed to download ${url} after ${retries} attempts."
  return 1
}
MUNITOR_HELPERS_EOF

cat > /tmp/munitor/extract_munitor_vars.sh << 'MUNITOR_EXTRACT_EOF'
#!/usr/bin/env bash
# Shared helper for extracting variables from .munitor.yml
# Source this file to get MUNITOR_* variables exported

set -euo pipefail

extract_munitor_vars() {
  local config_file="${1:-.munitor.yml}"

  if [[ ! -f "${config_file}" ]]; then
    echo "ERROR: Config file '${config_file}' not found." >&2
    return 1
  fi

  # --- Org defaults (overridable via .munitor.yml org section) ---
  local ORG_DOCKER_REGISTRY
  ORG_DOCKER_REGISTRY=$(yq '.org.docker_registry // "ghcr.io/KofTwentyTwo"' "${config_file}")
  local ORG_NPM_SCOPE
  ORG_NPM_SCOPE=$(yq '.org.npm_scope // "@koftwentytwo"' "${config_file}")
  local ORG_CI_EMAIL
  ORG_CI_EMAIL=$(yq '.org.ci_email // "munitor-ci@koftwentytwo.com"' "${config_file}")
  local ORG_CI_NAME
  ORG_CI_NAME=$(yq '.org.ci_name // "Munitor CI"' "${config_file}")
  local ORG_ORB_SLUG
  ORG_ORB_SLUG=$(yq '.org.orb_slug // "kof22/munitor"' "${config_file}")

  # Core pipeline settings
  MUNITOR_PIPELINE=$(yq '.pipeline' "${config_file}")
  MUNITOR_ORB_VERSION=$(yq '.orb_version // ""' "${config_file}")
  MUNITOR_IMAGE_NAME=$(yq '.image_name // ""' "${config_file}")
  MUNITOR_JAVA_VERSION=$(yq '.java_version // "21"' "${config_file}")
  MUNITOR_SERVER_MODULE=$(yq '.server_module // ""' "${config_file}")
  MUNITOR_NODE_VERSION=$(yq '.node_version // "20"' "${config_file}")
  MUNITOR_SONAR_PROJECT_KEY=$(yq '.sonar.project_key // ""' "${config_file}")
  MUNITOR_DOCKER_REGISTRY=$(yq '.docker.registry // ""' "${config_file}")
  if [[ -z "${MUNITOR_DOCKER_REGISTRY}" || "${MUNITOR_DOCKER_REGISTRY}" == "null" ]]; then
    MUNITOR_DOCKER_REGISTRY="${ORG_DOCKER_REGISTRY}"
  fi
  MUNITOR_CD_REPO=$(yq '.cd.repo // ""' "${config_file}")
  MUNITOR_CD_FORMAT=$(yq '.cd.format // "helm"' "${config_file}")
  MUNITOR_CD_ENV_DEVELOP=$(yq '.cd.env.develop // "develop"' "${config_file}")
  MUNITOR_CD_ENV_STAGING=$(yq '.cd.env.staging // "staging"' "${config_file}")
  MUNITOR_CD_ENV_PROD=$(yq '.cd.env.prod // "prod"' "${config_file}")
  MUNITOR_CD_ENV_RELEASE=$(yq '.cd.env.release // "staging"' "${config_file}")
  MUNITOR_COVERAGE_MIN=$(yq '.coverage.min_instruction // "70"' "${config_file}")
  MUNITOR_E2E=$(yq '.e2e // false' "${config_file}")
  MUNITOR_SBOM=$(yq '.sbom // false' "${config_file}")
  MUNITOR_OWASP=$(yq '.owasp' "${config_file}")
  if [[ "${MUNITOR_OWASP}" == "null" ]]; then
    MUNITOR_OWASP="true"
  fi

  # Contexts
  MUNITOR_CONTEXT_REGISTRY=$(yq '.contexts.registry // ""' "${config_file}")
  MUNITOR_CONTEXT_GITHUB=$(yq '.contexts.github // ""' "${config_file}")
  MUNITOR_CONTEXT_SONAR=$(yq '.contexts.sonar // ""' "${config_file}")
  MUNITOR_CONTEXT_NVD=$(yq '.contexts.nvd // ""' "${config_file}")

  # GitHub Release: auto-enabled when contexts.github is present
  if [[ -n "${MUNITOR_CONTEXT_GITHUB}" ]]; then
    MUNITOR_GITHUB_RELEASE="true"
  else
    MUNITOR_GITHUB_RELEASE="false"
  fi

  # Node-api extended features
  MUNITOR_NPM_AUTH=$(yq '.npm.private_registry // false' "${config_file}")
  MUNITOR_NPM_SCOPES=$(yq -o=json -I=0 '.npm.scopes // []' "${config_file}")
  MUNITOR_SERVICES_JSON=$(yq '.services // [] | tojson' "${config_file}")
  if [[ "${MUNITOR_SERVICES_JSON}" == "[]" ]]; then
    MUNITOR_SERVICES="false"
  else
    MUNITOR_SERVICES="true"
  fi
  MUNITOR_TEST_SETUP_SCRIPT=$(yq '.test.setup // ""' "${config_file}")
  if [[ -n "${MUNITOR_TEST_SETUP_SCRIPT}" ]]; then
    MUNITOR_TEST_SETUP="true"
  else
    MUNITOR_TEST_SETUP="false"
  fi
  MUNITOR_TEST_COMMANDS_JSON=$(yq '.test.commands // [] | tojson' "${config_file}")
  if [[ "${MUNITOR_TEST_COMMANDS_JSON}" == "[]" ]]; then
    MUNITOR_CUSTOM_TEST="false"
  else
    MUNITOR_CUSTOM_TEST="true"
  fi
  MUNITOR_COVERAGE_TOOL=$(yq '.test.coverage.tool // "jest"' "${config_file}")
  MUNITOR_COVERAGE_COMMAND=$(yq '.test.coverage.command // ""' "${config_file}")
  if [[ -n "${MUNITOR_COVERAGE_COMMAND}" ]]; then
    MUNITOR_COVERAGE_CMD="true"
  else
    MUNITOR_COVERAGE_CMD="false"
  fi
  # Allow test.coverage.min_instruction to override coverage.min_instruction
  MUNITOR_TEST_COVERAGE_MIN=$(yq '.test.coverage.min_instruction // ""' "${config_file}")
  if [[ -n "${MUNITOR_TEST_COVERAGE_MIN}" ]]; then
    MUNITOR_COVERAGE_MIN="${MUNITOR_TEST_COVERAGE_MIN}"
  fi
  MUNITOR_COVERAGE_SUMMARY_PATH=$(yq '.test.coverage.summary_path // "coverage/coverage-summary.json"' "${config_file}")

  # Terraform pipeline settings
  MUNITOR_TF_PATH=$(yq '.terraform.path // "terraform/"' "${config_file}")
  MUNITOR_TF_LIVE_PATH=$(yq '.terraform.live_path // "terraform/live"' "${config_file}")
  MUNITOR_TF_ENVIRONMENTS=$(yq '.terraform.environments // ["production"] | join(" ")' "${config_file}")
  MUNITOR_CHECKOV_SKIP=$(yq '.terraform.checkov_skip // ""' "${config_file}")
  # Kustomize / CD repo validation settings
  MUNITOR_KUSTOMIZE_VERSION=$(yq '.kustomize.version // "5.5.0"' "${config_file}")
  # Use 'has' check so explicit base_path: "" is preserved (yq // treats "" as falsy)
  if yq -e '.kustomize.base_path != null' "${config_file}" &>/dev/null; then
    MUNITOR_KUSTOMIZE_BASE_PATH=$(yq '.kustomize.base_path' "${config_file}")
  else
    MUNITOR_KUSTOMIZE_BASE_PATH="base/"
  fi
  MUNITOR_KUSTOMIZE_LOAD_RESTRICTOR=$(yq '.kustomize.load_restrictor // "true"' "${config_file}")
  MUNITOR_KUSTOMIZE_SCAN_OVERLAY=$(yq '.kustomize.scan_overlay // "production"' "${config_file}")
  MUNITOR_KUSTOMIZE_OVERLAYS=$(yq '.kustomize.overlays // [] | join(" ")' "${config_file}")
  MUNITOR_KUSTOMIZE_OVERLAY_DIR=$(yq '.kustomize.overlay_dir // "overlays"' "${config_file}")
  MUNITOR_KUBE_LINTER_CONFIG=$(yq '.kube_linter_config // ""' "${config_file}")
  MUNITOR_YAMLLINT_PATHS=$(yq '.yamllint_paths // ""' "${config_file}")
  if [[ -z "${MUNITOR_YAMLLINT_PATHS}" || "${MUNITOR_YAMLLINT_PATHS}" == "null" ]]; then
    case "${MUNITOR_PIPELINE}" in
      argocd-apps) MUNITOR_YAMLLINT_PATHS="bootstrap/ projects/ credentials/ envs/ apps/ infra/" ;;
      *) MUNITOR_YAMLLINT_PATHS="base/ overlays/ argocd-apps/" ;;
    esac
  fi

  # SAST: supports boolean (true/false) or object form (sast: { fail_on_findings: false })
  local sast_raw
  sast_raw=$(yq '.sast' "${config_file}")
  case "${sast_raw}" in
    true)
      MUNITOR_SAST="true"
      MUNITOR_SAST_FAIL_ON_FINDINGS="true"
      ;;
    false|null)
      MUNITOR_SAST="false"
      MUNITOR_SAST_FAIL_ON_FINDINGS="true"
      ;;
    *)
      # Object form: sast is present as a map, so SAST is enabled
      MUNITOR_SAST="true"
      local fof
      fof=$(yq '.sast.fail_on_findings' "${config_file}")
      if [[ "${fof}" == "false" ]]; then
        MUNITOR_SAST_FAIL_ON_FINDINGS="false"
      else
        MUNITOR_SAST_FAIL_ON_FINDINGS="true"
      fi
      ;;
  esac

  # Node framework (nextjs or express)
  MUNITOR_NODE_FRAMEWORK=$(yq '.node.framework // "nextjs"' "${config_file}")

  # Package manager (npm, yarn, pnpm)
  MUNITOR_PACKAGE_MANAGER=$(yq '.package_manager // "npm"' "${config_file}")

  # Org-level variables (derived from defaults block)
  MUNITOR_CI_EMAIL="${ORG_CI_EMAIL}"
  MUNITOR_CI_NAME="${ORG_CI_NAME}"
  MUNITOR_NPM_DEFAULT_SCOPE="${ORG_NPM_SCOPE}"
  MUNITOR_ORB_SLUG="${ORG_ORB_SLUG}"

  # Health check settings
  MUNITOR_HEALTH_PATH=$(yq '.health.path // "/api/health"' "${config_file}")
  MUNITOR_HEALTH_PORT=$(yq '.health.port // ""' "${config_file}")
  if [[ -z "${MUNITOR_HEALTH_PORT}" || "${MUNITOR_HEALTH_PORT}" == "null" ]]; then
    case "${MUNITOR_PIPELINE}" in
      node-api|node-webapp) MUNITOR_HEALTH_PORT="3000" ;;
      *) MUNITOR_HEALTH_PORT="8080" ;;
    esac
  fi
  MUNITOR_HEALTH_DB=$(yq '.health.db // false' "${config_file}")
  MUNITOR_HEALTH_MIGRATIONS=$(yq '.health.migrations // ""' "${config_file}")
  if [[ "${MUNITOR_HEALTH_MIGRATIONS}" == "null" ]]; then MUNITOR_HEALTH_MIGRATIONS=""; fi
  MUNITOR_HEALTH_SMOKE_PATHS=$(yq '.health.smoke_paths // [] | join(",")' "${config_file}")
  if [[ "${MUNITOR_HEALTH_SMOKE_PATHS}" == "null" ]]; then MUNITOR_HEALTH_SMOKE_PATHS=""; fi

  # Supplemental images (e.g., migrations, db-backup)
  MUNITOR_SUPPLEMENTAL_IMAGES_JSON=$(yq -o=json -I=0 '.supplemental_images // []' "${config_file}")
  if [[ "${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}" == "[]" || "${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}" == "null" ]]; then
    MUNITOR_SUPPLEMENTAL="false"
    MUNITOR_SUPPLEMENTAL_IMAGES_JSON="[]"
  else
    MUNITOR_SUPPLEMENTAL="true"
  fi

  # Derived flags
  if [[ -n "${MUNITOR_SONAR_PROJECT_KEY}" ]]; then
    MUNITOR_SONAR="true"
  else
    MUNITOR_SONAR="false"
  fi

  if [[ -n "${MUNITOR_CD_REPO}" ]]; then
    MUNITOR_CD="true"
  else
    MUNITOR_CD="false"
  fi

  if [[ -n "${MUNITOR_CONTEXT_NVD}" ]]; then
    MUNITOR_NVD="true"
  else
    MUNITOR_NVD="false"
  fi

  # Export all variables
  export MUNITOR_PIPELINE MUNITOR_ORB_VERSION MUNITOR_IMAGE_NAME MUNITOR_JAVA_VERSION MUNITOR_NODE_VERSION MUNITOR_SERVER_MODULE
  export MUNITOR_SONAR_PROJECT_KEY MUNITOR_DOCKER_REGISTRY MUNITOR_CD_REPO MUNITOR_CD_FORMAT
  export MUNITOR_CD_ENV_DEVELOP MUNITOR_CD_ENV_STAGING MUNITOR_CD_ENV_PROD MUNITOR_CD_ENV_RELEASE
  export MUNITOR_COVERAGE_MIN MUNITOR_E2E MUNITOR_SBOM MUNITOR_OWASP
  export MUNITOR_CONTEXT_REGISTRY MUNITOR_CONTEXT_GITHUB MUNITOR_CONTEXT_SONAR MUNITOR_CONTEXT_NVD
  export MUNITOR_GITHUB_RELEASE
  export MUNITOR_NPM_AUTH MUNITOR_NPM_SCOPES
  export MUNITOR_SERVICES MUNITOR_SERVICES_JSON
  export MUNITOR_TEST_SETUP MUNITOR_TEST_SETUP_SCRIPT
  export MUNITOR_CUSTOM_TEST MUNITOR_TEST_COMMANDS_JSON
  export MUNITOR_COVERAGE_TOOL MUNITOR_COVERAGE_CMD MUNITOR_COVERAGE_COMMAND MUNITOR_COVERAGE_SUMMARY_PATH
  export MUNITOR_TF_PATH MUNITOR_TF_LIVE_PATH MUNITOR_TF_ENVIRONMENTS MUNITOR_CHECKOV_SKIP MUNITOR_SAST MUNITOR_SAST_FAIL_ON_FINDINGS
  export MUNITOR_KUSTOMIZE_VERSION MUNITOR_KUSTOMIZE_BASE_PATH MUNITOR_KUSTOMIZE_LOAD_RESTRICTOR
  export MUNITOR_KUSTOMIZE_SCAN_OVERLAY MUNITOR_KUSTOMIZE_OVERLAYS MUNITOR_KUSTOMIZE_OVERLAY_DIR
  export MUNITOR_KUBE_LINTER_CONFIG MUNITOR_YAMLLINT_PATHS
  export MUNITOR_NODE_FRAMEWORK MUNITOR_PACKAGE_MANAGER
  export MUNITOR_CI_EMAIL MUNITOR_CI_NAME MUNITOR_NPM_DEFAULT_SCOPE MUNITOR_ORB_SLUG
  export MUNITOR_HEALTH_PATH MUNITOR_HEALTH_PORT MUNITOR_HEALTH_DB MUNITOR_HEALTH_MIGRATIONS MUNITOR_HEALTH_SMOKE_PATHS
  export MUNITOR_SUPPLEMENTAL MUNITOR_SUPPLEMENTAL_IMAGES_JSON
  export MUNITOR_SONAR MUNITOR_CD MUNITOR_NVD
}

# Build the envsubst variable list
get_envsubst_vars() {
  # shellcheck disable=SC2016
  echo '${MUNITOR_PIPELINE} ${MUNITOR_ORB_VERSION} ${MUNITOR_IMAGE_NAME} ${MUNITOR_JAVA_VERSION} ${MUNITOR_NODE_VERSION} ${MUNITOR_SONAR_PROJECT_KEY} ${MUNITOR_DOCKER_REGISTRY} ${MUNITOR_CD_REPO} ${MUNITOR_CD_FORMAT} ${MUNITOR_CD_ENV_DEVELOP} ${MUNITOR_CD_ENV_STAGING} ${MUNITOR_CD_ENV_PROD} ${MUNITOR_CD_ENV_RELEASE} ${MUNITOR_COVERAGE_MIN} ${MUNITOR_E2E} ${MUNITOR_SBOM} ${MUNITOR_OWASP} ${MUNITOR_CONTEXT_REGISTRY} ${MUNITOR_CONTEXT_GITHUB} ${MUNITOR_CONTEXT_SONAR} ${MUNITOR_CONTEXT_NVD} ${MUNITOR_NPM_AUTH} ${MUNITOR_NPM_SCOPES} ${MUNITOR_SERVICES_JSON} ${MUNITOR_TEST_SETUP_SCRIPT} ${MUNITOR_TEST_COMMANDS_JSON} ${MUNITOR_COVERAGE_TOOL} ${MUNITOR_COVERAGE_COMMAND} ${MUNITOR_GITHUB_RELEASE} ${MUNITOR_SAST} ${MUNITOR_SAST_FAIL_ON_FINDINGS} ${MUNITOR_HEALTH_PATH} ${MUNITOR_HEALTH_PORT} ${MUNITOR_HEALTH_DB} ${MUNITOR_HEALTH_MIGRATIONS} ${MUNITOR_HEALTH_SMOKE_PATHS} ${MUNITOR_TF_PATH} ${MUNITOR_TF_LIVE_PATH} ${MUNITOR_TF_ENVIRONMENTS} ${MUNITOR_CHECKOV_SKIP} ${MUNITOR_KUSTOMIZE_VERSION} ${MUNITOR_KUSTOMIZE_BASE_PATH} ${MUNITOR_KUSTOMIZE_LOAD_RESTRICTOR} ${MUNITOR_KUSTOMIZE_SCAN_OVERLAY} ${MUNITOR_KUSTOMIZE_OVERLAYS} ${MUNITOR_KUSTOMIZE_OVERLAY_DIR} ${MUNITOR_KUBE_LINTER_CONFIG} ${MUNITOR_YAMLLINT_PATHS} ${MUNITOR_CI_EMAIL} ${MUNITOR_CI_NAME} ${MUNITOR_NPM_DEFAULT_SCOPE} ${MUNITOR_ORB_SLUG} ${MUNITOR_PACKAGE_MANAGER} ${MUNITOR_SUPPLEMENTAL_IMAGES_JSON} ${MUNITOR_SERVER_MODULE} ${MUNITOR_COVERAGE_SUMMARY_PATH}'
}
MUNITOR_EXTRACT_EOF

cat > /tmp/munitor/templates/java-webapp.yml.tpl << 'MUNITOR_TPL_EOF'
version: 2.1

orbs:
  munitor: ${MUNITOR_ORB_SLUG}@${MUNITOR_ORB_VERSION}

workflows:
  pr-checks:
    jobs:
      - munitor/mvn_build_and_test:
          name: build-and-test
          java_version: "${MUNITOR_JAVA_VERSION}"
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/sast_scan:
          name: sast-scan
          fail_on_findings: "${MUNITOR_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/mvn_code_quality:
          name: code-quality
          java_version: "${MUNITOR_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/mvn_coverage:
          name: coverage
          java_version: "${MUNITOR_JAVA_VERSION}"
          min_instruction: "${MUNITOR_COVERAGE_MIN}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/security_scan:
          name: security-scan
          java_version: "${MUNITOR_JAVA_VERSION}"
          owasp: ${MUNITOR_OWASP}
          ##IF_OWASP##
          ##IF_NVD##
          context:
            - ${MUNITOR_CONTEXT_NVD}
          ##ENDIF_NVD##
          ##ENDIF_OWASP##
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      ##IF_E2E##
      - munitor/mvn_e2e_test:
          name: e2e-tests
          java_version: "${MUNITOR_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      ##ENDIF_E2E##

  ##INCLUDE_DEPLOY java-webapp-deploy develop develop ${MUNITOR_CD_ENV_DEVELOP}##
  ##INCLUDE_DEPLOY java-webapp-deploy staging staging ${MUNITOR_CD_ENV_STAGING}##

  release-candidate:
    jobs:
      - munitor/mvn_build_and_test:
          name: build-and-test
          java_version: "${MUNITOR_JAVA_VERSION}"
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/sast_scan:
          name: sast-scan
          fail_on_findings: "${MUNITOR_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/mvn_code_quality:
          name: code-quality
          java_version: "${MUNITOR_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/mvn_coverage:
          name: coverage
          java_version: "${MUNITOR_JAVA_VERSION}"
          min_instruction: "${MUNITOR_COVERAGE_MIN}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/security_scan:
          name: security-scan
          java_version: "${MUNITOR_JAVA_VERSION}"
          owasp: ${MUNITOR_OWASP}
          ##IF_OWASP##
          ##IF_NVD##
          context:
            - ${MUNITOR_CONTEXT_NVD}
          ##ENDIF_NVD##
          ##ENDIF_OWASP##
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      ##IF_E2E##
      - munitor/mvn_e2e_test:
          name: e2e-tests
          java_version: "${MUNITOR_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_E2E##
      ##IF_SONAR##
      - munitor/sonar_scan:
          name: sonar-scan
          java_version: "${MUNITOR_JAVA_VERSION}"
          sonar_project_key: ${MUNITOR_SONAR_PROJECT_KEY}
          requires:
            - build-and-test
            - coverage
          context:
            - ${MUNITOR_CONTEXT_SONAR}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_SONAR##
      - munitor/docker_build_push:
          name: docker-build-push
          image_name: ${MUNITOR_IMAGE_NAME}
          registry: ${MUNITOR_DOCKER_REGISTRY}
          health_path: ${MUNITOR_HEALTH_PATH}
          health_port: "${MUNITOR_HEALTH_PORT}"
          health_db: "${MUNITOR_HEALTH_DB}"
          health_migrations: "${MUNITOR_HEALTH_MIGRATIONS}"
          health_smoke_paths: "${MUNITOR_HEALTH_SMOKE_PATHS}"
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_SONAR##
            - sonar-scan
            ##ENDIF_SONAR##
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          context:
            - ${MUNITOR_CONTEXT_REGISTRY}
          filters:
            branches:
              only:
                - /release\/.*/
      ##IF_SBOM##
      - munitor/sbom:
          name: sbom
          java_version: "${MUNITOR_JAVA_VERSION}"
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_SONAR##
            - sonar-scan
            ##ENDIF_SONAR##
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_SBOM##
      ##IF_CD##
      - munitor/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${MUNITOR_CD_REPO}
          environment: ${MUNITOR_CD_ENV_RELEASE}
          cd_format: ${MUNITOR_CD_FORMAT}
          cd_image_name: ${MUNITOR_DOCKER_REGISTRY}/${MUNITOR_IMAGE_NAME}
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          ci_git_email: '${MUNITOR_CI_EMAIL}'
          ci_git_name: '${MUNITOR_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_CD##
      ##IF_GITHUB_RELEASE##
      - munitor/github_release:
          name: github-release
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_GITHUB_RELEASE##

  production:
    jobs:
      - munitor/mvn_build_and_test:
          name: build-and-test
          java_version: "${MUNITOR_JAVA_VERSION}"
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      - munitor/docker_build_push:
          name: docker-build-push
          image_name: ${MUNITOR_IMAGE_NAME}
          registry: ${MUNITOR_DOCKER_REGISTRY}
          health_path: ${MUNITOR_HEALTH_PATH}
          health_port: "${MUNITOR_HEALTH_PORT}"
          health_db: "${MUNITOR_HEALTH_DB}"
          health_migrations: "${MUNITOR_HEALTH_MIGRATIONS}"
          health_smoke_paths: "${MUNITOR_HEALTH_SMOKE_PATHS}"
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          requires:
            - build-and-test
          context:
            - ${MUNITOR_CONTEXT_REGISTRY}
          filters:
            branches:
              only: main
      ##IF_CD##
      - munitor/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${MUNITOR_CD_REPO}
          environment: ${MUNITOR_CD_ENV_PROD}
          cd_format: ${MUNITOR_CD_FORMAT}
          cd_image_name: ${MUNITOR_DOCKER_REGISTRY}/${MUNITOR_IMAGE_NAME}
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          ci_git_email: '${MUNITOR_CI_EMAIL}'
          ci_git_name: '${MUNITOR_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      ##ENDIF_CD##
      ##IF_GITHUB_RELEASE##
      - munitor/github_release:
          name: github-release
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      ##ENDIF_GITHUB_RELEASE##
MUNITOR_TPL_EOF

cat > /tmp/munitor/templates/gradle-webapp.yml.tpl << 'MUNITOR_TPL_EOF'
version: 2.1

orbs:
  munitor: ${MUNITOR_ORB_SLUG}@${MUNITOR_ORB_VERSION}

workflows:
  pr-checks:
    jobs:
      - munitor/gradle_build_and_test:
          name: build-and-test
          java_version: "${MUNITOR_JAVA_VERSION}"
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/sast_scan:
          name: sast-scan
          fail_on_findings: "${MUNITOR_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/gradle_code_quality:
          name: code-quality
          java_version: "${MUNITOR_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/gradle_coverage:
          name: coverage
          java_version: "${MUNITOR_JAVA_VERSION}"
          min_instruction: "${MUNITOR_COVERAGE_MIN}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/security_scan:
          name: security-scan
          java_version: "${MUNITOR_JAVA_VERSION}"
          owasp: ${MUNITOR_OWASP}
          ##IF_OWASP##
          ##IF_NVD##
          context:
            - ${MUNITOR_CONTEXT_NVD}
          ##ENDIF_NVD##
          ##ENDIF_OWASP##
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      ##IF_E2E##
      - munitor/mvn_e2e_test:
          name: e2e-tests
          java_version: "${MUNITOR_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      ##ENDIF_E2E##

  ##INCLUDE_DEPLOY gradle-webapp-deploy develop develop ${MUNITOR_CD_ENV_DEVELOP}##
  ##INCLUDE_DEPLOY gradle-webapp-deploy staging staging ${MUNITOR_CD_ENV_STAGING}##

  release-candidate:
    jobs:
      - munitor/gradle_build_and_test:
          name: build-and-test
          java_version: "${MUNITOR_JAVA_VERSION}"
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/sast_scan:
          name: sast-scan
          fail_on_findings: "${MUNITOR_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/gradle_code_quality:
          name: code-quality
          java_version: "${MUNITOR_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/gradle_coverage:
          name: coverage
          java_version: "${MUNITOR_JAVA_VERSION}"
          min_instruction: "${MUNITOR_COVERAGE_MIN}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/security_scan:
          name: security-scan
          java_version: "${MUNITOR_JAVA_VERSION}"
          owasp: ${MUNITOR_OWASP}
          ##IF_OWASP##
          ##IF_NVD##
          context:
            - ${MUNITOR_CONTEXT_NVD}
          ##ENDIF_NVD##
          ##ENDIF_OWASP##
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      ##IF_E2E##
      - munitor/mvn_e2e_test:
          name: e2e-tests
          java_version: "${MUNITOR_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_E2E##
      ##IF_SONAR##
      - munitor/sonar_scan:
          name: sonar-scan
          java_version: "${MUNITOR_JAVA_VERSION}"
          sonar_project_key: ${MUNITOR_SONAR_PROJECT_KEY}
          requires:
            - build-and-test
            - coverage
          context:
            - ${MUNITOR_CONTEXT_SONAR}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_SONAR##
      - munitor/docker_build_push:
          name: docker-build-push
          image_name: ${MUNITOR_IMAGE_NAME}
          registry: ${MUNITOR_DOCKER_REGISTRY}
          health_path: ${MUNITOR_HEALTH_PATH}
          health_port: "${MUNITOR_HEALTH_PORT}"
          health_db: "${MUNITOR_HEALTH_DB}"
          health_migrations: "${MUNITOR_HEALTH_MIGRATIONS}"
          health_smoke_paths: "${MUNITOR_HEALTH_SMOKE_PATHS}"
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_SONAR##
            - sonar-scan
            ##ENDIF_SONAR##
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          context:
            - ${MUNITOR_CONTEXT_REGISTRY}
          filters:
            branches:
              only:
                - /release\/.*/
      ##IF_SBOM##
      - munitor/sbom:
          name: sbom
          java_version: "${MUNITOR_JAVA_VERSION}"
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_SONAR##
            - sonar-scan
            ##ENDIF_SONAR##
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_SBOM##
      ##IF_CD##
      - munitor/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${MUNITOR_CD_REPO}
          environment: ${MUNITOR_CD_ENV_RELEASE}
          cd_format: ${MUNITOR_CD_FORMAT}
          cd_image_name: ${MUNITOR_DOCKER_REGISTRY}/${MUNITOR_IMAGE_NAME}
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          ci_git_email: '${MUNITOR_CI_EMAIL}'
          ci_git_name: '${MUNITOR_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_CD##
      ##IF_GITHUB_RELEASE##
      - munitor/github_release:
          name: github-release
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_GITHUB_RELEASE##

  production:
    jobs:
      - munitor/gradle_build_and_test:
          name: build-and-test
          java_version: "${MUNITOR_JAVA_VERSION}"
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      - munitor/docker_build_push:
          name: docker-build-push
          image_name: ${MUNITOR_IMAGE_NAME}
          registry: ${MUNITOR_DOCKER_REGISTRY}
          health_path: ${MUNITOR_HEALTH_PATH}
          health_port: "${MUNITOR_HEALTH_PORT}"
          health_db: "${MUNITOR_HEALTH_DB}"
          health_migrations: "${MUNITOR_HEALTH_MIGRATIONS}"
          health_smoke_paths: "${MUNITOR_HEALTH_SMOKE_PATHS}"
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          requires:
            - build-and-test
          context:
            - ${MUNITOR_CONTEXT_REGISTRY}
          filters:
            branches:
              only: main
      ##IF_CD##
      - munitor/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${MUNITOR_CD_REPO}
          environment: ${MUNITOR_CD_ENV_PROD}
          cd_format: ${MUNITOR_CD_FORMAT}
          cd_image_name: ${MUNITOR_DOCKER_REGISTRY}/${MUNITOR_IMAGE_NAME}
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          ci_git_email: '${MUNITOR_CI_EMAIL}'
          ci_git_name: '${MUNITOR_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      ##ENDIF_CD##
      ##IF_GITHUB_RELEASE##
      - munitor/github_release:
          name: github-release
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      ##ENDIF_GITHUB_RELEASE##
MUNITOR_TPL_EOF

cat > /tmp/munitor/templates/node-api.yml.tpl << 'MUNITOR_TPL_EOF'
version: 2.1

orbs:
  munitor: ${MUNITOR_ORB_SLUG}@${MUNITOR_ORB_VERSION}

workflows:
  pr-checks:
    jobs:
      - munitor/node_build_and_test:
          name: build-and-test
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          ##IF_NPM_AUTH##
          npm_auth: true
          npm_scopes: '${MUNITOR_NPM_SCOPES}'
          npm_default_scope: '${MUNITOR_NPM_DEFAULT_SCOPE}'
          ##ENDIF_NPM_AUTH##
          ##IF_SERVICES##
          services: '${MUNITOR_SERVICES_JSON}'
          ##ENDIF_SERVICES##
          ##IF_TEST_SETUP##
          test_setup: ${MUNITOR_TEST_SETUP_SCRIPT}
          ##ENDIF_TEST_SETUP##
          ##IF_CUSTOM_TEST##
          test_commands: '${MUNITOR_TEST_COMMANDS_JSON}'
          ##ENDIF_CUSTOM_TEST##
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/sast_scan:
          name: sast-scan
          fail_on_findings: "${MUNITOR_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/node_code_quality:
          name: code-quality
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/node_coverage:
          name: coverage
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          min_coverage: "${MUNITOR_COVERAGE_MIN}"
          coverage_tool: ${MUNITOR_COVERAGE_TOOL}
          coverage_summary_path: "${MUNITOR_COVERAGE_SUMMARY_PATH}"
          ##IF_COVERAGE_CMD##
          coverage_command: ${MUNITOR_COVERAGE_COMMAND}
          ##ENDIF_COVERAGE_CMD##
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/node_security_scan:
          name: security-scan
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      ##IF_E2E##
      - munitor/node_e2e_test:
          name: e2e-tests
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      ##ENDIF_E2E##

  ##INCLUDE_DEPLOY node-api-deploy develop develop ${MUNITOR_CD_ENV_DEVELOP}##
  ##INCLUDE_DEPLOY node-api-deploy staging staging ${MUNITOR_CD_ENV_STAGING}##

  release-candidate:
    jobs:
      - munitor/node_build_and_test:
          name: build-and-test
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          ##IF_NPM_AUTH##
          npm_auth: true
          npm_scopes: '${MUNITOR_NPM_SCOPES}'
          npm_default_scope: '${MUNITOR_NPM_DEFAULT_SCOPE}'
          ##ENDIF_NPM_AUTH##
          ##IF_SERVICES##
          services: '${MUNITOR_SERVICES_JSON}'
          ##ENDIF_SERVICES##
          ##IF_TEST_SETUP##
          test_setup: ${MUNITOR_TEST_SETUP_SCRIPT}
          ##ENDIF_TEST_SETUP##
          ##IF_CUSTOM_TEST##
          test_commands: '${MUNITOR_TEST_COMMANDS_JSON}'
          ##ENDIF_CUSTOM_TEST##
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/sast_scan:
          name: sast-scan
          fail_on_findings: "${MUNITOR_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/node_code_quality:
          name: code-quality
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/node_coverage:
          name: coverage
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          min_coverage: "${MUNITOR_COVERAGE_MIN}"
          coverage_tool: ${MUNITOR_COVERAGE_TOOL}
          coverage_summary_path: "${MUNITOR_COVERAGE_SUMMARY_PATH}"
          ##IF_COVERAGE_CMD##
          coverage_command: ${MUNITOR_COVERAGE_COMMAND}
          ##ENDIF_COVERAGE_CMD##
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/node_security_scan:
          name: security-scan
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      ##IF_E2E##
      - munitor/node_e2e_test:
          name: e2e-tests
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_E2E##
      ##IF_SONAR##
      - munitor/node_sonar_scan:
          name: sonar-scan
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          sonar_project_key: ${MUNITOR_SONAR_PROJECT_KEY}
          requires:
            - build-and-test
            - coverage
          context:
            - ${MUNITOR_CONTEXT_SONAR}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_SONAR##
      - munitor/docker_build_push:
          name: docker-build-push
          image_name: ${MUNITOR_IMAGE_NAME}
          registry: ${MUNITOR_DOCKER_REGISTRY}
          health_path: ${MUNITOR_HEALTH_PATH}
          health_port: "${MUNITOR_HEALTH_PORT}"
          health_db: "${MUNITOR_HEALTH_DB}"
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          context:
            - ${MUNITOR_CONTEXT_REGISTRY}
          filters:
            branches:
              only:
                - /release\/.*/
      ##IF_SBOM##
      - munitor/node_sbom:
          name: sbom
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_SBOM##
      ##IF_CD##
      - munitor/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${MUNITOR_CD_REPO}
          environment: ${MUNITOR_CD_ENV_RELEASE}
          cd_format: ${MUNITOR_CD_FORMAT}
          cd_image_name: ${MUNITOR_DOCKER_REGISTRY}/${MUNITOR_IMAGE_NAME}
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          ci_git_email: '${MUNITOR_CI_EMAIL}'
          ci_git_name: '${MUNITOR_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_CD##
      ##IF_GITHUB_RELEASE##
      - munitor/github_release:
          name: github-release
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_GITHUB_RELEASE##

  production:
    jobs:
      - munitor/node_build_and_test:
          name: build-and-test
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          ##IF_NPM_AUTH##
          npm_auth: true
          npm_scopes: '${MUNITOR_NPM_SCOPES}'
          npm_default_scope: '${MUNITOR_NPM_DEFAULT_SCOPE}'
          ##ENDIF_NPM_AUTH##
          ##IF_SERVICES##
          services: '${MUNITOR_SERVICES_JSON}'
          ##ENDIF_SERVICES##
          ##IF_TEST_SETUP##
          test_setup: ${MUNITOR_TEST_SETUP_SCRIPT}
          ##ENDIF_TEST_SETUP##
          ##IF_CUSTOM_TEST##
          test_commands: '${MUNITOR_TEST_COMMANDS_JSON}'
          ##ENDIF_CUSTOM_TEST##
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      - munitor/docker_build_push:
          name: docker-build-push
          image_name: ${MUNITOR_IMAGE_NAME}
          registry: ${MUNITOR_DOCKER_REGISTRY}
          health_path: ${MUNITOR_HEALTH_PATH}
          health_port: "${MUNITOR_HEALTH_PORT}"
          health_db: "${MUNITOR_HEALTH_DB}"
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          requires:
            - build-and-test
          context:
            - ${MUNITOR_CONTEXT_REGISTRY}
          filters:
            branches:
              only: main
      ##IF_CD##
      - munitor/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${MUNITOR_CD_REPO}
          environment: ${MUNITOR_CD_ENV_PROD}
          cd_format: ${MUNITOR_CD_FORMAT}
          cd_image_name: ${MUNITOR_DOCKER_REGISTRY}/${MUNITOR_IMAGE_NAME}
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          ci_git_email: '${MUNITOR_CI_EMAIL}'
          ci_git_name: '${MUNITOR_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      ##ENDIF_CD##
      ##IF_GITHUB_RELEASE##
      - munitor/github_release:
          name: github-release
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      ##ENDIF_GITHUB_RELEASE##
MUNITOR_TPL_EOF

cat > /tmp/munitor/templates/node-webapp.yml.tpl << 'MUNITOR_TPL_EOF'
version: 2.1

orbs:
  munitor: ${MUNITOR_ORB_SLUG}@${MUNITOR_ORB_VERSION}

workflows:
  pr-checks:
    jobs:
      - munitor/node_build_and_test:
          name: build-and-test
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          ##IF_NPM_AUTH##
          npm_auth: true
          npm_scopes: '${MUNITOR_NPM_SCOPES}'
          npm_default_scope: '${MUNITOR_NPM_DEFAULT_SCOPE}'
          ##ENDIF_NPM_AUTH##
          ##IF_SERVICES##
          services: '${MUNITOR_SERVICES_JSON}'
          ##ENDIF_SERVICES##
          ##IF_TEST_SETUP##
          test_setup: ${MUNITOR_TEST_SETUP_SCRIPT}
          ##ENDIF_TEST_SETUP##
          ##IF_CUSTOM_TEST##
          test_commands: '${MUNITOR_TEST_COMMANDS_JSON}'
          ##ENDIF_CUSTOM_TEST##
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/sast_scan:
          name: sast-scan
          fail_on_findings: "${MUNITOR_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/node_code_quality:
          name: code-quality
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/node_coverage:
          name: coverage
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          min_coverage: "${MUNITOR_COVERAGE_MIN}"
          coverage_tool: ${MUNITOR_COVERAGE_TOOL}
          coverage_summary_path: "${MUNITOR_COVERAGE_SUMMARY_PATH}"
          ##IF_COVERAGE_CMD##
          coverage_command: ${MUNITOR_COVERAGE_COMMAND}
          ##ENDIF_COVERAGE_CMD##
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/node_security_scan:
          name: security-scan
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      ##IF_E2E##
      - munitor/node_e2e_test:
          name: e2e-tests
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      ##ENDIF_E2E##

  ##INCLUDE_DEPLOY node-webapp-deploy develop develop ${MUNITOR_CD_ENV_DEVELOP}##
  ##INCLUDE_DEPLOY node-webapp-deploy staging staging ${MUNITOR_CD_ENV_STAGING}##

  release-candidate:
    jobs:
      - munitor/node_build_and_test:
          name: build-and-test
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          ##IF_NPM_AUTH##
          npm_auth: true
          npm_scopes: '${MUNITOR_NPM_SCOPES}'
          npm_default_scope: '${MUNITOR_NPM_DEFAULT_SCOPE}'
          ##ENDIF_NPM_AUTH##
          ##IF_SERVICES##
          services: '${MUNITOR_SERVICES_JSON}'
          ##ENDIF_SERVICES##
          ##IF_TEST_SETUP##
          test_setup: ${MUNITOR_TEST_SETUP_SCRIPT}
          ##ENDIF_TEST_SETUP##
          ##IF_CUSTOM_TEST##
          test_commands: '${MUNITOR_TEST_COMMANDS_JSON}'
          ##ENDIF_CUSTOM_TEST##
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/sast_scan:
          name: sast-scan
          fail_on_findings: "${MUNITOR_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/node_code_quality:
          name: code-quality
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/node_coverage:
          name: coverage
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          min_coverage: "${MUNITOR_COVERAGE_MIN}"
          coverage_tool: ${MUNITOR_COVERAGE_TOOL}
          coverage_summary_path: "${MUNITOR_COVERAGE_SUMMARY_PATH}"
          ##IF_COVERAGE_CMD##
          coverage_command: ${MUNITOR_COVERAGE_COMMAND}
          ##ENDIF_COVERAGE_CMD##
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/node_security_scan:
          name: security-scan
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      ##IF_E2E##
      - munitor/node_e2e_test:
          name: e2e-tests
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_E2E##
      ##IF_SONAR##
      - munitor/node_sonar_scan:
          name: sonar-scan
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          sonar_project_key: ${MUNITOR_SONAR_PROJECT_KEY}
          requires:
            - build-and-test
            - coverage
          context:
            - ${MUNITOR_CONTEXT_SONAR}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_SONAR##
      - munitor/docker_build_push:
          name: docker-build-push
          image_name: ${MUNITOR_IMAGE_NAME}
          registry: ${MUNITOR_DOCKER_REGISTRY}
          health_path: ${MUNITOR_HEALTH_PATH}
          health_port: "${MUNITOR_HEALTH_PORT}"
          health_db: "${MUNITOR_HEALTH_DB}"
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          context:
            - ${MUNITOR_CONTEXT_REGISTRY}
          filters:
            branches:
              only:
                - /release\/.*/
      ##IF_SBOM##
      - munitor/node_sbom:
          name: sbom
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_SBOM##
      ##IF_CD##
      - munitor/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${MUNITOR_CD_REPO}
          environment: ${MUNITOR_CD_ENV_RELEASE}
          cd_format: ${MUNITOR_CD_FORMAT}
          cd_image_name: ${MUNITOR_DOCKER_REGISTRY}/${MUNITOR_IMAGE_NAME}
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          ci_git_email: '${MUNITOR_CI_EMAIL}'
          ci_git_name: '${MUNITOR_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_CD##
      ##IF_GITHUB_RELEASE##
      - munitor/github_release:
          name: github-release
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_GITHUB_RELEASE##

  production:
    jobs:
      - munitor/node_build_and_test:
          name: build-and-test
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          ##IF_NPM_AUTH##
          npm_auth: true
          npm_scopes: '${MUNITOR_NPM_SCOPES}'
          npm_default_scope: '${MUNITOR_NPM_DEFAULT_SCOPE}'
          ##ENDIF_NPM_AUTH##
          ##IF_SERVICES##
          services: '${MUNITOR_SERVICES_JSON}'
          ##ENDIF_SERVICES##
          ##IF_TEST_SETUP##
          test_setup: ${MUNITOR_TEST_SETUP_SCRIPT}
          ##ENDIF_TEST_SETUP##
          ##IF_CUSTOM_TEST##
          test_commands: '${MUNITOR_TEST_COMMANDS_JSON}'
          ##ENDIF_CUSTOM_TEST##
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      - munitor/docker_build_push:
          name: docker-build-push
          image_name: ${MUNITOR_IMAGE_NAME}
          registry: ${MUNITOR_DOCKER_REGISTRY}
          health_path: ${MUNITOR_HEALTH_PATH}
          health_port: "${MUNITOR_HEALTH_PORT}"
          health_db: "${MUNITOR_HEALTH_DB}"
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          requires:
            - build-and-test
          context:
            - ${MUNITOR_CONTEXT_REGISTRY}
          filters:
            branches:
              only: main
      ##IF_CD##
      - munitor/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${MUNITOR_CD_REPO}
          environment: ${MUNITOR_CD_ENV_PROD}
          cd_format: ${MUNITOR_CD_FORMAT}
          cd_image_name: ${MUNITOR_DOCKER_REGISTRY}/${MUNITOR_IMAGE_NAME}
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          ci_git_email: '${MUNITOR_CI_EMAIL}'
          ci_git_name: '${MUNITOR_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      ##ENDIF_CD##
      ##IF_GITHUB_RELEASE##
      - munitor/github_release:
          name: github-release
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      ##ENDIF_GITHUB_RELEASE##
MUNITOR_TPL_EOF

cat > /tmp/munitor/templates/terraform.yml.tpl << 'MUNITOR_TPL_EOF'
version: 2.1

orbs:
  munitor: ${MUNITOR_ORB_SLUG}@${MUNITOR_ORB_VERSION}

workflows:
  pr-checks:
    jobs:
      - munitor/validate_repo:
          name: validate-repo
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/tf_validate:
          name: tf-validate
          environments: "${MUNITOR_TF_ENVIRONMENTS}"
          tf_path: ${MUNITOR_TF_PATH}
          base_path: ${MUNITOR_TF_LIVE_PATH}
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/tf_security_scan:
          name: tf-security-scan
          tf_path: ${MUNITOR_TF_PATH}
          checkov_skip: ${MUNITOR_CHECKOV_SKIP}
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      ##IF_SAST##
      - munitor/sast_scan:
          name: sast-scan
          fail_on_findings: "${MUNITOR_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      ##ENDIF_SAST##

  develop:
    jobs:
      - munitor/validate_repo:
          name: validate-repo
          filters:
            branches:
              only: develop
      - munitor/tf_validate:
          name: tf-validate
          environments: "${MUNITOR_TF_ENVIRONMENTS}"
          tf_path: ${MUNITOR_TF_PATH}
          base_path: ${MUNITOR_TF_LIVE_PATH}
          filters:
            branches:
              only: develop
      - munitor/tf_security_scan:
          name: tf-security-scan
          tf_path: ${MUNITOR_TF_PATH}
          checkov_skip: ${MUNITOR_CHECKOV_SKIP}
          filters:
            branches:
              only: develop
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only: develop
      ##IF_SAST##
      - munitor/sast_scan:
          name: sast-scan
          fail_on_findings: "${MUNITOR_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only: develop
      ##ENDIF_SAST##

  release-candidate:
    jobs:
      - munitor/validate_repo:
          name: validate-repo
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/tf_validate:
          name: tf-validate
          environments: "${MUNITOR_TF_ENVIRONMENTS}"
          tf_path: ${MUNITOR_TF_PATH}
          base_path: ${MUNITOR_TF_LIVE_PATH}
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/tf_security_scan:
          name: tf-security-scan
          tf_path: ${MUNITOR_TF_PATH}
          checkov_skip: ${MUNITOR_CHECKOV_SKIP}
          filters:
            branches:
              only:
                - /release\/.*/
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /release\/.*/
      ##IF_SAST##
      - munitor/sast_scan:
          name: sast-scan
          fail_on_findings: "${MUNITOR_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_SAST##

  production:
    jobs:
      - munitor/validate_repo:
          name: validate-repo
          filters:
            branches:
              only: main
      - munitor/tf_validate:
          name: tf-validate
          environments: "${MUNITOR_TF_ENVIRONMENTS}"
          tf_path: ${MUNITOR_TF_PATH}
          base_path: ${MUNITOR_TF_LIVE_PATH}
          filters:
            branches:
              only: main
MUNITOR_TPL_EOF

cat > /tmp/munitor/templates/sdk-distribution.yml.tpl << 'MUNITOR_TPL_EOF'
version: 2.1

orbs:
  munitor: ${MUNITOR_ORB_SLUG}@${MUNITOR_ORB_VERSION}

workflows:
  pr-validate:
    when:
      not:
        equal: [main, << pipeline.git.branch >>]
    jobs:
      - munitor/secrets_scan:
          name: secrets-scan

  release:
    jobs:
      - munitor/sdk_release:
          name: sdk-release
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
MUNITOR_TPL_EOF

cat > /tmp/munitor/templates/validate-cd-repo.yml.tpl << 'MUNITOR_TPL_EOF'
version: 2.1

orbs:
  munitor: ${MUNITOR_ORB_SLUG}@${MUNITOR_ORB_VERSION}

workflows:
  pr-checks:
    jobs:
      - munitor/yaml_lint_cd:
          name: yaml-lint
          paths: "${MUNITOR_YAMLLINT_PATHS}"
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/kustomize_validate:
          name: kustomize-validate
          kustomize_version: "${MUNITOR_KUSTOMIZE_VERSION}"
          base_path: "${MUNITOR_KUSTOMIZE_BASE_PATH}"
          overlays: "${MUNITOR_KUSTOMIZE_OVERLAYS}"
          load_restrictor: "${MUNITOR_KUSTOMIZE_LOAD_RESTRICTOR}"
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/kubesec_scan:
          name: kubesec-scan
          scan_overlay: "${MUNITOR_KUSTOMIZE_SCAN_OVERLAY}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/kube_linter:
          name: kube-linter
          scan_overlay: "${MUNITOR_KUSTOMIZE_SCAN_OVERLAY}"
          config: "${MUNITOR_KUBE_LINTER_CONFIG}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/

  develop:
    jobs:
      - munitor/yaml_lint_cd:
          name: yaml-lint
          paths: "${MUNITOR_YAMLLINT_PATHS}"
          filters:
            branches:
              only: develop
      - munitor/kustomize_validate:
          name: kustomize-validate
          kustomize_version: "${MUNITOR_KUSTOMIZE_VERSION}"
          base_path: "${MUNITOR_KUSTOMIZE_BASE_PATH}"
          overlays: "${MUNITOR_KUSTOMIZE_OVERLAYS}"
          load_restrictor: "${MUNITOR_KUSTOMIZE_LOAD_RESTRICTOR}"
          filters:
            branches:
              only: develop
      - munitor/kubesec_scan:
          name: kubesec-scan
          scan_overlay: "${MUNITOR_KUSTOMIZE_SCAN_OVERLAY}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only: develop
      - munitor/kube_linter:
          name: kube-linter
          scan_overlay: "${MUNITOR_KUSTOMIZE_SCAN_OVERLAY}"
          config: "${MUNITOR_KUBE_LINTER_CONFIG}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only: develop
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only: develop

  release:
    jobs:
      - munitor/yaml_lint_cd:
          name: yaml-lint
          paths: "${MUNITOR_YAMLLINT_PATHS}"
          filters:
            branches:
              only: main
      - munitor/kustomize_validate:
          name: kustomize-validate
          kustomize_version: "${MUNITOR_KUSTOMIZE_VERSION}"
          base_path: "${MUNITOR_KUSTOMIZE_BASE_PATH}"
          overlays: "${MUNITOR_KUSTOMIZE_OVERLAYS}"
          load_restrictor: "${MUNITOR_KUSTOMIZE_LOAD_RESTRICTOR}"
          filters:
            branches:
              only: main
      - munitor/kubesec_scan:
          name: kubesec-scan
          scan_overlay: "${MUNITOR_KUSTOMIZE_SCAN_OVERLAY}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only: main
      - munitor/kube_linter:
          name: kube-linter
          scan_overlay: "${MUNITOR_KUSTOMIZE_SCAN_OVERLAY}"
          config: "${MUNITOR_KUBE_LINTER_CONFIG}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only: main
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only: main
MUNITOR_TPL_EOF

cat > /tmp/munitor/templates/argocd-apps.yml.tpl << 'MUNITOR_TPL_EOF'
version: 2.1

orbs:
  munitor: ${MUNITOR_ORB_SLUG}@${MUNITOR_ORB_VERSION}

workflows:
  pr-checks:
    jobs:
      - munitor/yaml_lint_cd:
          name: yaml-lint
          paths: "${MUNITOR_YAMLLINT_PATHS}"
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/kustomize_validate:
          name: kustomize-validate
          kustomize_version: "${MUNITOR_KUSTOMIZE_VERSION}"
          base_path: "${MUNITOR_KUSTOMIZE_BASE_PATH}"
          overlay_dir: "${MUNITOR_KUSTOMIZE_OVERLAY_DIR}"
          overlays: "${MUNITOR_KUSTOMIZE_OVERLAYS}"
          load_restrictor: "${MUNITOR_KUSTOMIZE_LOAD_RESTRICTOR}"
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/kubesec_scan:
          name: kubesec-scan
          scan_overlay: "${MUNITOR_KUSTOMIZE_SCAN_OVERLAY}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/kube_linter:
          name: kube-linter
          scan_overlay: "${MUNITOR_KUSTOMIZE_SCAN_OVERLAY}"
          config: "${MUNITOR_KUBE_LINTER_CONFIG}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/

  develop:
    jobs:
      - munitor/yaml_lint_cd:
          name: yaml-lint
          paths: "${MUNITOR_YAMLLINT_PATHS}"
          filters:
            branches:
              only: develop
      - munitor/kustomize_validate:
          name: kustomize-validate
          kustomize_version: "${MUNITOR_KUSTOMIZE_VERSION}"
          base_path: "${MUNITOR_KUSTOMIZE_BASE_PATH}"
          overlay_dir: "${MUNITOR_KUSTOMIZE_OVERLAY_DIR}"
          overlays: "${MUNITOR_KUSTOMIZE_OVERLAYS}"
          load_restrictor: "${MUNITOR_KUSTOMIZE_LOAD_RESTRICTOR}"
          filters:
            branches:
              only: develop
      - munitor/kubesec_scan:
          name: kubesec-scan
          scan_overlay: "${MUNITOR_KUSTOMIZE_SCAN_OVERLAY}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only: develop
      - munitor/kube_linter:
          name: kube-linter
          scan_overlay: "${MUNITOR_KUSTOMIZE_SCAN_OVERLAY}"
          config: "${MUNITOR_KUBE_LINTER_CONFIG}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only: develop
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only: develop

  release:
    jobs:
      - munitor/yaml_lint_cd:
          name: yaml-lint
          paths: "${MUNITOR_YAMLLINT_PATHS}"
          filters:
            branches:
              only: main
      - munitor/kustomize_validate:
          name: kustomize-validate
          kustomize_version: "${MUNITOR_KUSTOMIZE_VERSION}"
          base_path: "${MUNITOR_KUSTOMIZE_BASE_PATH}"
          overlay_dir: "${MUNITOR_KUSTOMIZE_OVERLAY_DIR}"
          overlays: "${MUNITOR_KUSTOMIZE_OVERLAYS}"
          load_restrictor: "${MUNITOR_KUSTOMIZE_LOAD_RESTRICTOR}"
          filters:
            branches:
              only: main
      - munitor/kubesec_scan:
          name: kubesec-scan
          scan_overlay: "${MUNITOR_KUSTOMIZE_SCAN_OVERLAY}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only: main
      - munitor/kube_linter:
          name: kube-linter
          scan_overlay: "${MUNITOR_KUSTOMIZE_SCAN_OVERLAY}"
          config: "${MUNITOR_KUBE_LINTER_CONFIG}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only: main
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only: main
MUNITOR_TPL_EOF

cat > /tmp/munitor/templates/partials/java-webapp-deploy.yml.tpl << 'MUNITOR_PARTIAL_EOF'
  __WORKFLOW_NAME__:
    jobs:
      - munitor/mvn_build_and_test:
          name: build-and-test
          java_version: "${MUNITOR_JAVA_VERSION}"
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/sast_scan:
          name: sast-scan
          fail_on_findings: "${MUNITOR_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/mvn_code_quality:
          name: code-quality
          java_version: "${MUNITOR_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/mvn_coverage:
          name: coverage
          java_version: "${MUNITOR_JAVA_VERSION}"
          min_instruction: "${MUNITOR_COVERAGE_MIN}"
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/security_scan:
          name: security-scan
          java_version: "${MUNITOR_JAVA_VERSION}"
          owasp: ${MUNITOR_OWASP}
          ##IF_OWASP##
          ##IF_NVD##
          context:
            - ${MUNITOR_CONTEXT_NVD}
          ##ENDIF_NVD##
          ##ENDIF_OWASP##
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##IF_E2E##
      - munitor/mvn_e2e_test:
          name: e2e-tests
          java_version: "${MUNITOR_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_E2E##
      ##IF_SONAR##
      - munitor/sonar_scan:
          name: sonar-scan
          java_version: "${MUNITOR_JAVA_VERSION}"
          sonar_project_key: ${MUNITOR_SONAR_PROJECT_KEY}
          requires:
            - build-and-test
            - coverage
          context:
            - ${MUNITOR_CONTEXT_SONAR}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_SONAR##
      - munitor/docker_build_push:
          name: docker-build-push
          image_name: ${MUNITOR_IMAGE_NAME}
          registry: ${MUNITOR_DOCKER_REGISTRY}
          health_path: ${MUNITOR_HEALTH_PATH}
          health_port: "${MUNITOR_HEALTH_PORT}"
          health_db: "${MUNITOR_HEALTH_DB}"
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_SONAR##
            - sonar-scan
            ##ENDIF_SONAR##
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          context:
            - ${MUNITOR_CONTEXT_REGISTRY}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##IF_SBOM##
      - munitor/sbom:
          name: sbom
          java_version: "${MUNITOR_JAVA_VERSION}"
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_SONAR##
            - sonar-scan
            ##ENDIF_SONAR##
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_SBOM##
      ##IF_CD##
      - munitor/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${MUNITOR_CD_REPO}
          environment: __CD_ENVIRONMENT__
          cd_format: ${MUNITOR_CD_FORMAT}
          cd_image_name: ${MUNITOR_DOCKER_REGISTRY}/${MUNITOR_IMAGE_NAME}
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          ci_git_email: '${MUNITOR_CI_EMAIL}'
          ci_git_name: '${MUNITOR_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_CD##
MUNITOR_PARTIAL_EOF

cat > /tmp/munitor/templates/partials/gradle-webapp-deploy.yml.tpl << 'MUNITOR_PARTIAL_EOF'
  __WORKFLOW_NAME__:
    jobs:
      - munitor/gradle_build_and_test:
          name: build-and-test
          java_version: "${MUNITOR_JAVA_VERSION}"
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/sast_scan:
          name: sast-scan
          fail_on_findings: "${MUNITOR_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/gradle_code_quality:
          name: code-quality
          java_version: "${MUNITOR_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/gradle_coverage:
          name: coverage
          java_version: "${MUNITOR_JAVA_VERSION}"
          min_instruction: "${MUNITOR_COVERAGE_MIN}"
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/security_scan:
          name: security-scan
          java_version: "${MUNITOR_JAVA_VERSION}"
          owasp: ${MUNITOR_OWASP}
          ##IF_OWASP##
          ##IF_NVD##
          context:
            - ${MUNITOR_CONTEXT_NVD}
          ##ENDIF_NVD##
          ##ENDIF_OWASP##
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##IF_E2E##
      - munitor/mvn_e2e_test:
          name: e2e-tests
          java_version: "${MUNITOR_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_E2E##
      ##IF_SONAR##
      - munitor/sonar_scan:
          name: sonar-scan
          java_version: "${MUNITOR_JAVA_VERSION}"
          sonar_project_key: ${MUNITOR_SONAR_PROJECT_KEY}
          requires:
            - build-and-test
            - coverage
          context:
            - ${MUNITOR_CONTEXT_SONAR}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_SONAR##
      - munitor/docker_build_push:
          name: docker-build-push
          image_name: ${MUNITOR_IMAGE_NAME}
          registry: ${MUNITOR_DOCKER_REGISTRY}
          health_path: ${MUNITOR_HEALTH_PATH}
          health_port: "${MUNITOR_HEALTH_PORT}"
          health_db: "${MUNITOR_HEALTH_DB}"
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_SONAR##
            - sonar-scan
            ##ENDIF_SONAR##
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          context:
            - ${MUNITOR_CONTEXT_REGISTRY}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##IF_SBOM##
      - munitor/sbom:
          name: sbom
          java_version: "${MUNITOR_JAVA_VERSION}"
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_SONAR##
            - sonar-scan
            ##ENDIF_SONAR##
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_SBOM##
      ##IF_CD##
      - munitor/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${MUNITOR_CD_REPO}
          environment: __CD_ENVIRONMENT__
          cd_format: ${MUNITOR_CD_FORMAT}
          cd_image_name: ${MUNITOR_DOCKER_REGISTRY}/${MUNITOR_IMAGE_NAME}
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          ci_git_email: '${MUNITOR_CI_EMAIL}'
          ci_git_name: '${MUNITOR_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_CD##
MUNITOR_PARTIAL_EOF

cat > /tmp/munitor/templates/partials/node-api-deploy.yml.tpl << 'MUNITOR_PARTIAL_EOF'
  __WORKFLOW_NAME__:
    jobs:
      - munitor/node_build_and_test:
          name: build-and-test
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          ##IF_NPM_AUTH##
          npm_auth: true
          npm_scopes: '${MUNITOR_NPM_SCOPES}'
          npm_default_scope: '${MUNITOR_NPM_DEFAULT_SCOPE}'
          ##ENDIF_NPM_AUTH##
          ##IF_SERVICES##
          services: '${MUNITOR_SERVICES_JSON}'
          ##ENDIF_SERVICES##
          ##IF_TEST_SETUP##
          test_setup: ${MUNITOR_TEST_SETUP_SCRIPT}
          ##ENDIF_TEST_SETUP##
          ##IF_CUSTOM_TEST##
          test_commands: '${MUNITOR_TEST_COMMANDS_JSON}'
          ##ENDIF_CUSTOM_TEST##
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/sast_scan:
          name: sast-scan
          fail_on_findings: "${MUNITOR_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/node_code_quality:
          name: code-quality
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/node_coverage:
          name: coverage
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          min_coverage: "${MUNITOR_COVERAGE_MIN}"
          coverage_tool: ${MUNITOR_COVERAGE_TOOL}
          coverage_summary_path: "${MUNITOR_COVERAGE_SUMMARY_PATH}"
          ##IF_COVERAGE_CMD##
          coverage_command: ${MUNITOR_COVERAGE_COMMAND}
          ##ENDIF_COVERAGE_CMD##
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/node_security_scan:
          name: security-scan
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##IF_E2E##
      - munitor/node_e2e_test:
          name: e2e-tests
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_E2E##
      ##IF_SONAR##
      - munitor/node_sonar_scan:
          name: sonar-scan
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          sonar_project_key: ${MUNITOR_SONAR_PROJECT_KEY}
          requires:
            - build-and-test
            - coverage
          context:
            - ${MUNITOR_CONTEXT_SONAR}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_SONAR##
      - munitor/docker_build_push:
          name: docker-build-push
          image_name: ${MUNITOR_IMAGE_NAME}
          registry: ${MUNITOR_DOCKER_REGISTRY}
          health_path: ${MUNITOR_HEALTH_PATH}
          health_port: "${MUNITOR_HEALTH_PORT}"
          health_db: "${MUNITOR_HEALTH_DB}"
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          context:
            - ${MUNITOR_CONTEXT_REGISTRY}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##IF_SBOM##
      - munitor/node_sbom:
          name: sbom
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_SBOM##
      ##IF_CD##
      - munitor/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${MUNITOR_CD_REPO}
          environment: __CD_ENVIRONMENT__
          cd_format: ${MUNITOR_CD_FORMAT}
          cd_image_name: ${MUNITOR_DOCKER_REGISTRY}/${MUNITOR_IMAGE_NAME}
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          ci_git_email: '${MUNITOR_CI_EMAIL}'
          ci_git_name: '${MUNITOR_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_CD##
MUNITOR_PARTIAL_EOF

cat > /tmp/munitor/templates/partials/node-webapp-deploy.yml.tpl << 'MUNITOR_PARTIAL_EOF'
  __WORKFLOW_NAME__:
    jobs:
      - munitor/node_build_and_test:
          name: build-and-test
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          ##IF_NPM_AUTH##
          npm_auth: true
          npm_scopes: '${MUNITOR_NPM_SCOPES}'
          npm_default_scope: '${MUNITOR_NPM_DEFAULT_SCOPE}'
          ##ENDIF_NPM_AUTH##
          ##IF_SERVICES##
          services: '${MUNITOR_SERVICES_JSON}'
          ##ENDIF_SERVICES##
          ##IF_TEST_SETUP##
          test_setup: ${MUNITOR_TEST_SETUP_SCRIPT}
          ##ENDIF_TEST_SETUP##
          ##IF_CUSTOM_TEST##
          test_commands: '${MUNITOR_TEST_COMMANDS_JSON}'
          ##ENDIF_CUSTOM_TEST##
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/sast_scan:
          name: sast-scan
          fail_on_findings: "${MUNITOR_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/node_code_quality:
          name: code-quality
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/node_coverage:
          name: coverage
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          min_coverage: "${MUNITOR_COVERAGE_MIN}"
          coverage_tool: ${MUNITOR_COVERAGE_TOOL}
          coverage_summary_path: "${MUNITOR_COVERAGE_SUMMARY_PATH}"
          ##IF_COVERAGE_CMD##
          coverage_command: ${MUNITOR_COVERAGE_COMMAND}
          ##ENDIF_COVERAGE_CMD##
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      - munitor/node_security_scan:
          name: security-scan
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##IF_E2E##
      - munitor/node_e2e_test:
          name: e2e-tests
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_E2E##
      ##IF_SONAR##
      - munitor/node_sonar_scan:
          name: sonar-scan
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          sonar_project_key: ${MUNITOR_SONAR_PROJECT_KEY}
          requires:
            - build-and-test
            - coverage
          context:
            - ${MUNITOR_CONTEXT_SONAR}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_SONAR##
      - munitor/docker_build_push:
          name: docker-build-push
          image_name: ${MUNITOR_IMAGE_NAME}
          registry: ${MUNITOR_DOCKER_REGISTRY}
          health_path: ${MUNITOR_HEALTH_PATH}
          health_port: "${MUNITOR_HEALTH_PORT}"
          health_db: "${MUNITOR_HEALTH_DB}"
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          context:
            - ${MUNITOR_CONTEXT_REGISTRY}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##IF_SBOM##
      - munitor/node_sbom:
          name: sbom
          node_version: "${MUNITOR_NODE_VERSION}"
          package_manager: "${MUNITOR_PACKAGE_MANAGER}"
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_SBOM##
      ##IF_CD##
      - munitor/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${MUNITOR_CD_REPO}
          environment: __CD_ENVIRONMENT__
          cd_format: ${MUNITOR_CD_FORMAT}
          cd_image_name: ${MUNITOR_DOCKER_REGISTRY}/${MUNITOR_IMAGE_NAME}
          ##IF_SUPPLEMENTAL##
          supplemental_images: '${MUNITOR_SUPPLEMENTAL_IMAGES_JSON}'
          ##ENDIF_SUPPLEMENTAL##
          ci_git_email: '${MUNITOR_CI_EMAIL}'
          ci_git_name: '${MUNITOR_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${MUNITOR_CONTEXT_GITHUB}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_CD##
MUNITOR_PARTIAL_EOF

echo "Munitor helpers staged to /tmp/munitor/"

# ======================================================================
# Main generate_config.sh logic
# ======================================================================

set -euo pipefail

CONFIG_FILE="${MUNITOR_CONFIG:-.munitor.yml}"
OUTPUT_FILE="/tmp/generated-config.yml"

# When run via CircleCI << include() >>, BASH_SOURCE is empty.
# Fall back to MUNITOR_SCRIPT_DIR set by the command YAML.
if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
else
  SCRIPT_DIR="${MUNITOR_SCRIPT_DIR:-/tmp/munitor}"
fi
TEMPLATE_DIR="${SCRIPT_DIR}/templates"

# Source shared helpers
MUNITOR_HELPERS="${MUNITOR_HELPERS:-${SCRIPT_DIR}/munitor_helpers.sh}"
# shellcheck source=munitor_helpers.sh
if [[ -f "${MUNITOR_HELPERS}" ]]; then source "${MUNITOR_HELPERS}"
elif ! type munitor_header &>/dev/null; then
  munitor_header() { echo "=== Munitor: ${1:-unknown} ==="; }
  munitor_check_tool() { command -v "$1" &>/dev/null || { echo "ERROR: $1 not found"; exit 1; }; }
  munitor_download_with_retry() { curl -fsSL --retry 3 "$1" -o "$2"; }
fi

munitor_header "generate_config"
munitor_check_tool yq --version
munitor_check_tool envsubst --version

# Temp file cleanup trap
TEMP_FILES=()
cleanup() {
  for f in "${TEMP_FILES[@]}"; do
    rm -f "${f}" 2>/dev/null || true
  done
}
trap cleanup EXIT

# Source shared variable extraction
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/extract_munitor_vars.sh"

# --------------------------------------------------------------------------
# Read .munitor.yml
# --------------------------------------------------------------------------
if [[ ! -f "${CONFIG_FILE}" ]]; then
  echo "ERROR: Config file '${CONFIG_FILE}' not found."
  echo "Each repo must have a .munitor.yml in the root."
  exit 1
fi

PIPELINE_TYPE=$(yq '.pipeline' "${CONFIG_FILE}")

if [[ -z "${PIPELINE_TYPE}" || "${PIPELINE_TYPE}" == "null" ]]; then
  echo "ERROR: 'pipeline' field is required in ${CONFIG_FILE}."
  exit 1
fi

echo "Pipeline type: ${PIPELINE_TYPE}"

# --------------------------------------------------------------------------
# Validate required fields per pipeline type
# --------------------------------------------------------------------------
validate_required_fields() {
  local pipeline="$1"
  local config="$2"
  local missing=()

  # Global required fields (all pipeline types)
  [[ -z "$(yq '.orb_version // ""' "${config}")" ]] && missing+=("orb_version")

  case "${pipeline}" in
    java-webapp|gradle-webapp|node-api|node-webapp)
      [[ -z "$(yq '.image_name // ""' "${config}")" ]] && missing+=("image_name")
      [[ -z "$(yq '.docker.registry // ""' "${config}")" ]] && missing+=("docker.registry")
      ;;
    terraform)
      [[ -z "$(yq '.terraform.path // ""' "${config}")" ]] && missing+=("terraform.path")
      ;;
    validate-cd-repo|argocd-apps)
      # No additional required fields beyond orb_version
      ;;
  esac

  if [[ ${#missing[@]} -gt 0 ]]; then
    echo "ERROR: Missing required fields for pipeline '${pipeline}':"
    printf '  - %s\n' "${missing[@]}"
    return 1
  fi
}

validate_required_fields "${PIPELINE_TYPE}" "${CONFIG_FILE}"

# --------------------------------------------------------------------------
# Warn about unknown top-level keys (catches typos like java_verion)
# --------------------------------------------------------------------------
KNOWN_KEYS="pipeline orb_version image_name server_module java_version node_version sonar docker cd coverage e2e sbom owasp contexts npm node services test terraform sast health kustomize kube_linter_config package_manager yamllint_paths supplemental_images"
ACTUAL_KEYS=$(yq 'keys | .[]' "${CONFIG_FILE}" 2>/dev/null || true)
for key in ${ACTUAL_KEYS}; do
  if ! echo "${KNOWN_KEYS}" | grep -qw "${key}"; then
    echo "WARNING: Unknown key '${key}' in ${CONFIG_FILE} (possible typo?)"
  fi
done

# --------------------------------------------------------------------------
# Select template
# --------------------------------------------------------------------------
TEMPLATE_FILE="${TEMPLATE_DIR}/${PIPELINE_TYPE}.yml.tpl"

if [[ ! -f "${TEMPLATE_FILE}" ]]; then
  echo "ERROR: No template found for pipeline type '${PIPELINE_TYPE}'."
  echo "Available templates:"
  find "${TEMPLATE_DIR}" -maxdepth 1 -name '*.yml.tpl' -exec basename {} .yml.tpl \; 2>/dev/null | sed 's/^/  /'
  exit 1
fi

echo "Using template: ${TEMPLATE_FILE}"

# --------------------------------------------------------------------------
# Extract values from .munitor.yml and export for envsubst
# --------------------------------------------------------------------------
extract_munitor_vars "${CONFIG_FILE}"

# --------------------------------------------------------------------------
# Render template
# --------------------------------------------------------------------------

# Pre-pass: expand ##INCLUDE_DEPLOY <partial> <workflow> <branch> <cd_env>## markers
# Loads partial templates from templates/partials/ and substitutes placeholders
expand_includes() {
  local input="$1"
  local output="$2"
  local partials_dir="${TEMPLATE_DIR}/partials"
  local result
  result=$(mktemp)
  TEMP_FILES+=("${result}")

  cp "${input}" "${result}"

  while IFS= read -r line; do
    if [[ "${line}" =~ ^[[:space:]]*##INCLUDE_DEPLOY[[:space:]]+([^[:space:]]+)[[:space:]]+([^[:space:]]+)[[:space:]]+([^[:space:]]+)[[:space:]]+([^[:space:]]+)##[[:space:]]*$ ]]; then
      local partial="${BASH_REMATCH[1]}"
      local workflow="${BASH_REMATCH[2]}"
      local branch="${BASH_REMATCH[3]}"
      local cd_env="${BASH_REMATCH[4]}"
      local partial_file="${partials_dir}/${partial}.yml.tpl"

      if [[ ! -f "${partial_file}" ]]; then
        echo "ERROR: Partial template '${partial_file}' not found." >&2
        return 1
      fi

      local expanded
      expanded=$(mktemp)
      TEMP_FILES+=("${expanded}")
      sed \
        -e "s/__WORKFLOW_NAME__/${workflow}/g" \
        -e "s/__BRANCH_FILTER__/${branch}/g" \
        -e "s/__CD_ENVIRONMENT__/${cd_env}/g" \
        "${partial_file}" > "${expanded}"

      # Replace the marker line with the expanded partial content
      local swap
      swap=$(mktemp)
      TEMP_FILES+=("${swap}")
      awk -v marker="${line}" -v file="${expanded}" '
        $0 == marker { while ((getline rep < file) > 0) print rep; next }
        { print }
      ' "${result}" > "${swap}"
      cp "${swap}" "${result}"
    fi
  done < "${input}"

  cp "${result}" "${output}"
}

STAGE0_FILE=$(mktemp)
TEMP_FILES+=("${STAGE0_FILE}")
expand_includes "${TEMPLATE_FILE}" "${STAGE0_FILE}"

# Get the list of envsubst variables to replace
ENVSUBST_VARS=$(get_envsubst_vars)

# First pass: envsubst for variable replacement
STAGE1_FILE=$(mktemp)
TEMP_FILES+=("${STAGE1_FILE}")
envsubst "${ENVSUBST_VARS}" < "${STAGE0_FILE}" > "${STAGE1_FILE}"

# Second pass: process conditional blocks
# Removes blocks wrapped in ##IF_<FLAG>## / ##ENDIF_<FLAG>## when flag is false
process_conditionals() {
  local input="$1"
  local output="$2"
  local tmpfile
  tmpfile=$(mktemp)
  TEMP_FILES+=("${tmpfile}")

  cp "${input}" "${tmpfile}"

  # Process each conditional flag
  for flag in E2E SBOM SONAR NPM_AUTH SERVICES TEST_SETUP CUSTOM_TEST COVERAGE_CMD GITHUB_RELEASE SAST CD OWASP NVD SUPPLEMENTAL; do
    local var_name="MUNITOR_${flag}"
    local value="${!var_name:-false}"
    local flag_file
    flag_file=$(mktemp)
    TEMP_FILES+=("${flag_file}")

    if [[ "${value}" == "true" ]]; then
      # Keep the content, strip the markers
      sed "/^[[:space:]]*##IF_${flag}##[[:space:]]*$/d; /^[[:space:]]*##ENDIF_${flag}##[[:space:]]*$/d" "${tmpfile}" > "${flag_file}"
    else
      # Remove everything between markers (inclusive)
      awk "/^[[:space:]]*##IF_${flag}##[[:space:]]*$/{skip=1; next} /^[[:space:]]*##ENDIF_${flag}##[[:space:]]*$/{skip=0; next} !skip" "${tmpfile}" > "${flag_file}"
    fi

    cp "${flag_file}" "${tmpfile}"
  done

  cp "${tmpfile}" "${output}"
}

process_conditionals "${STAGE1_FILE}" "${OUTPUT_FILE}"

# Check for unprocessed conditional markers (indicates typo or unmatched pair)
STALE_MARKERS=$(grep -nE '##(IF|ENDIF)_[A-Z_]+##' "${OUTPUT_FILE}" || true)
if [[ -n "${STALE_MARKERS}" ]]; then
  echo "ERROR: Unprocessed conditional markers found in generated config:"
  echo "${STALE_MARKERS}"
  echo "This usually means a typo in a marker name or an unmatched IF/ENDIF pair."
  exit 1
fi

# Validate the generated YAML
if ! yq '.' "${OUTPUT_FILE}" > /dev/null 2>&1; then
  echo "ERROR: Generated config is not valid YAML"
  echo "Check template and conditional markers for mismatches"
  exit 1
fi

# Validate output file was actually created
if [[ ! -s "${OUTPUT_FILE}" ]]; then
  echo "ERROR: Generated config file is empty or missing at ${OUTPUT_FILE}."
  exit 1
fi

echo "Generated config written to: ${OUTPUT_FILE}"
echo "---"
head -20 "${OUTPUT_FILE}"
echo "..."
echo "($(wc -l < "${OUTPUT_FILE}") total lines)"
