#!/usr/bin/env bash
set -euo pipefail

# ======================================================================
# AUTO-GENERATED by scripts/pack_generate_config.sh
# Do not edit directly. Edit src/scripts/*.sh and re-pack.
# ======================================================================

# Stage helper files to /tmp/faber/ so generate_config.sh can find them
mkdir -p /tmp/faber/templates/partials

cat > /tmp/faber/faber_helpers.sh << 'FABER_HELPERS_EOF'
#!/usr/bin/env bash
# Shared helper library for Faber orb scripts.
# Source this at the top of each script for consistent diagnostics.
#
# Sourcing pattern (works even if helpers are missing):
#   FABER_HELPERS="${FABER_HELPERS:-$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)/faber_helpers.sh}"
#   [[ -f "${FABER_HELPERS}" ]] && source "${FABER_HELPERS}"

# Guard against double-sourcing
[[ -n "${_FABER_HELPERS_LOADED:-}" ]] && return 0
_FABER_HELPERS_LOADED=1

# --------------------------------------------------------------------------
# faber_header <step_name>
#
# Print a standard banner with date, hostname, and working directory.
# --------------------------------------------------------------------------
faber_header() {
  local name="${1:-unknown}"
  echo "========================================"
  echo "  Faber: ${name}"
  echo "  Date:  $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
  echo "  Host:  $(hostname 2>/dev/null || echo 'unknown')"
  echo "  Dir:   $(pwd)"
  echo "========================================"
}

# --------------------------------------------------------------------------
# faber_check_tool <command> [version_flag]
#
# Verify a tool is in PATH and print its version.  Exits 1 with a clear
# message if the tool is missing.
# --------------------------------------------------------------------------
faber_check_tool() {
  local cmd="$1"
  local version_flag="${2:---version}"

  if ! command -v "${cmd}" &>/dev/null; then
    echo "ERROR: Required tool '${cmd}' is not installed or not in PATH."
    echo "  PATH: ${PATH}"
    exit 1
  fi

  local ver
  ver=$("${cmd}" "${version_flag}" 2>&1 | head -1) || true
  echo "  ${cmd}: ${ver}"
}

# --------------------------------------------------------------------------
# faber_download_with_retry <url> <output> [retries] [delay]
#
# Download a URL with retry logic. Tries curl first, falls back to wget.
# --------------------------------------------------------------------------
faber_download_with_retry() {
  local url="$1"
  local output="$2"
  local retries="${3:-3}"
  local delay="${4:-5}"

  for attempt in $(seq 1 "${retries}"); do
    if command -v curl &>/dev/null; then
      if curl -fsSL --retry 2 "${url}" -o "${output}"; then
        return 0
      fi
    elif command -v wget &>/dev/null; then
      if wget -q "${url}" -O "${output}"; then
        return 0
      fi
    else
      echo "ERROR: Neither curl nor wget is available."
      exit 1
    fi

    if [[ "${attempt}" -lt "${retries}" ]]; then
      echo "  Download failed (attempt ${attempt}/${retries}), retrying in ${delay}s..."
      sleep "${delay}"
    fi
  done

  echo "ERROR: Failed to download ${url} after ${retries} attempts."
  return 1
}
FABER_HELPERS_EOF

cat > /tmp/faber/extract_faber_vars.sh << 'FABER_EXTRACT_EOF'
#!/usr/bin/env bash
# Shared helper for extracting variables from .faber.yml
# Source this file to get FABER_* variables exported

set -euo pipefail

extract_faber_vars() {
  local config_file="${1:-.faber.yml}"

  if [[ ! -f "${config_file}" ]]; then
    echo "ERROR: Config file '${config_file}' not found." >&2
    return 1
  fi

  # --- Org defaults (change this block when forking for another org) ---
  local ORG_DOCKER_REGISTRY="ghcr.io/dmdbrands"
  local ORG_NPM_SCOPE="@dmdbrands"
  local ORG_CI_EMAIL="faber-ci@dmdbrands.com"
  local ORG_CI_NAME="Faber CI"
  local ORG_ORB_SLUG="dmdbrands/faber"

  # Core pipeline settings
  FABER_PIPELINE=$(yq '.pipeline' "${config_file}")
  FABER_ORB_VERSION=$(yq '.orb_version // ""' "${config_file}")
  FABER_IMAGE_NAME=$(yq '.image_name // ""' "${config_file}")
  FABER_JAVA_VERSION=$(yq '.java_version // "21"' "${config_file}")
  FABER_NODE_VERSION=$(yq '.node_version // "20"' "${config_file}")
  FABER_SONAR_PROJECT_KEY=$(yq '.sonar.project_key // ""' "${config_file}")
  FABER_DOCKER_REGISTRY=$(yq '.docker.registry // ""' "${config_file}")
  if [[ -z "${FABER_DOCKER_REGISTRY}" || "${FABER_DOCKER_REGISTRY}" == "null" ]]; then
    FABER_DOCKER_REGISTRY="${ORG_DOCKER_REGISTRY}"
  fi
  FABER_CD_REPO=$(yq '.cd.repo // ""' "${config_file}")
  FABER_CD_FORMAT=$(yq '.cd.format // "helm"' "${config_file}")
  FABER_CD_ENV_DEVELOP=$(yq '.cd.env.develop // "develop"' "${config_file}")
  FABER_CD_ENV_STAGING=$(yq '.cd.env.staging // "staging"' "${config_file}")
  FABER_CD_ENV_PROD=$(yq '.cd.env.prod // "prod"' "${config_file}")
  FABER_CD_ENV_RELEASE=$(yq '.cd.env.release // "staging"' "${config_file}")
  FABER_COVERAGE_MIN=$(yq '.coverage.min_instruction // "70"' "${config_file}")
  FABER_E2E=$(yq '.e2e // false' "${config_file}")
  FABER_SBOM=$(yq '.sbom // false' "${config_file}")

  # Contexts
  FABER_CONTEXT_REGISTRY=$(yq '.contexts.registry // ""' "${config_file}")
  FABER_CONTEXT_GITHUB=$(yq '.contexts.github // ""' "${config_file}")
  FABER_CONTEXT_SONAR=$(yq '.contexts.sonar // ""' "${config_file}")
  FABER_CONTEXT_NVD=$(yq '.contexts.nvd // ""' "${config_file}")

  # GitHub Release: auto-enabled when contexts.github is present
  if [[ -n "${FABER_CONTEXT_GITHUB}" ]]; then
    FABER_GITHUB_RELEASE="true"
  else
    FABER_GITHUB_RELEASE="false"
  fi

  # Node-api extended features
  FABER_NPM_AUTH=$(yq '.npm.private_registry // false' "${config_file}")
  FABER_NPM_SCOPES=$(yq -o=json -I=0 '.npm.scopes // []' "${config_file}")
  FABER_SERVICES_JSON=$(yq '.services // [] | tojson' "${config_file}")
  if [[ "${FABER_SERVICES_JSON}" == "[]" ]]; then
    FABER_SERVICES="false"
  else
    FABER_SERVICES="true"
  fi
  FABER_TEST_SETUP_SCRIPT=$(yq '.test.setup // ""' "${config_file}")
  if [[ -n "${FABER_TEST_SETUP_SCRIPT}" ]]; then
    FABER_TEST_SETUP="true"
  else
    FABER_TEST_SETUP="false"
  fi
  FABER_TEST_COMMANDS_JSON=$(yq '.test.commands // [] | tojson' "${config_file}")
  if [[ "${FABER_TEST_COMMANDS_JSON}" == "[]" ]]; then
    FABER_CUSTOM_TEST="false"
  else
    FABER_CUSTOM_TEST="true"
  fi
  FABER_COVERAGE_TOOL=$(yq '.test.coverage.tool // "jest"' "${config_file}")
  FABER_COVERAGE_COMMAND=$(yq '.test.coverage.command // ""' "${config_file}")
  if [[ -n "${FABER_COVERAGE_COMMAND}" ]]; then
    FABER_COVERAGE_CMD="true"
  else
    FABER_COVERAGE_CMD="false"
  fi
  # Allow test.coverage.min_instruction to override coverage.min_instruction
  FABER_TEST_COVERAGE_MIN=$(yq '.test.coverage.min_instruction // ""' "${config_file}")
  if [[ -n "${FABER_TEST_COVERAGE_MIN}" ]]; then
    FABER_COVERAGE_MIN="${FABER_TEST_COVERAGE_MIN}"
  fi

  # Terraform pipeline settings
  FABER_TF_PATH=$(yq '.terraform.path // "terraform/"' "${config_file}")
  FABER_TF_LIVE_PATH=$(yq '.terraform.live_path // "terraform/live"' "${config_file}")
  FABER_TF_ENVIRONMENTS=$(yq '.terraform.environments // ["production"] | join(" ")' "${config_file}")
  FABER_CHECKOV_SKIP=$(yq '.terraform.checkov_skip // ""' "${config_file}")
  # Kustomize / CD repo validation settings
  FABER_KUSTOMIZE_VERSION=$(yq '.kustomize.version // "5.5.0"' "${config_file}")
  FABER_KUSTOMIZE_BASE_PATH=$(yq '.kustomize.base_path // "base/"' "${config_file}")
  FABER_KUSTOMIZE_LOAD_RESTRICTOR=$(yq '.kustomize.load_restrictor // "true"' "${config_file}")
  FABER_KUSTOMIZE_SCAN_OVERLAY=$(yq '.kustomize.scan_overlay // "production"' "${config_file}")
  FABER_KUSTOMIZE_OVERLAYS=$(yq '.kustomize.overlays // [] | join(" ")' "${config_file}")
  FABER_KUBE_LINTER_CONFIG=$(yq '.kube_linter_config // ""' "${config_file}")
  FABER_YAMLLINT_PATHS="base/ overlays/ argocd-apps/"

  # SAST: supports boolean (true/false) or object form (sast: { fail_on_findings: false })
  local sast_raw
  sast_raw=$(yq '.sast' "${config_file}")
  case "${sast_raw}" in
    true)
      FABER_SAST="true"
      FABER_SAST_FAIL_ON_FINDINGS="true"
      ;;
    false|null)
      FABER_SAST="false"
      FABER_SAST_FAIL_ON_FINDINGS="true"
      ;;
    *)
      # Object form: sast is present as a map, so SAST is enabled
      FABER_SAST="true"
      local fof
      fof=$(yq '.sast.fail_on_findings' "${config_file}")
      if [[ "${fof}" == "false" ]]; then
        FABER_SAST_FAIL_ON_FINDINGS="false"
      else
        FABER_SAST_FAIL_ON_FINDINGS="true"
      fi
      ;;
  esac

  # Node framework (nextjs or express)
  FABER_NODE_FRAMEWORK=$(yq '.node.framework // "nextjs"' "${config_file}")

  # Org-level variables (derived from defaults block)
  FABER_CI_EMAIL="${ORG_CI_EMAIL}"
  FABER_CI_NAME="${ORG_CI_NAME}"
  FABER_NPM_DEFAULT_SCOPE="${ORG_NPM_SCOPE}"
  FABER_ORB_SLUG="${ORG_ORB_SLUG}"

  # Health check settings
  FABER_HEALTH_PATH=$(yq '.health.path // "/api/health"' "${config_file}")
  FABER_HEALTH_PORT=$(yq '.health.port // ""' "${config_file}")
  if [[ -z "${FABER_HEALTH_PORT}" || "${FABER_HEALTH_PORT}" == "null" ]]; then
    case "${FABER_PIPELINE}" in
      node-api) FABER_HEALTH_PORT="3000" ;;
      *) FABER_HEALTH_PORT="8080" ;;
    esac
  fi
  FABER_HEALTH_DB=$(yq '.health.db // false' "${config_file}")

  # Derived flags
  if [[ -n "${FABER_SONAR_PROJECT_KEY}" ]]; then
    FABER_SONAR="true"
  else
    FABER_SONAR="false"
  fi

  if [[ -n "${FABER_CD_REPO}" ]]; then
    FABER_CD="true"
  else
    FABER_CD="false"
  fi

  # Export all variables
  export FABER_PIPELINE FABER_ORB_VERSION FABER_IMAGE_NAME FABER_JAVA_VERSION FABER_NODE_VERSION
  export FABER_SONAR_PROJECT_KEY FABER_DOCKER_REGISTRY FABER_CD_REPO FABER_CD_FORMAT
  export FABER_CD_ENV_DEVELOP FABER_CD_ENV_STAGING FABER_CD_ENV_PROD FABER_CD_ENV_RELEASE
  export FABER_COVERAGE_MIN FABER_E2E FABER_SBOM
  export FABER_CONTEXT_REGISTRY FABER_CONTEXT_GITHUB FABER_CONTEXT_SONAR FABER_CONTEXT_NVD
  export FABER_GITHUB_RELEASE
  export FABER_NPM_AUTH FABER_NPM_SCOPES
  export FABER_SERVICES FABER_SERVICES_JSON
  export FABER_TEST_SETUP FABER_TEST_SETUP_SCRIPT
  export FABER_CUSTOM_TEST FABER_TEST_COMMANDS_JSON
  export FABER_COVERAGE_TOOL FABER_COVERAGE_CMD FABER_COVERAGE_COMMAND
  export FABER_TF_PATH FABER_TF_LIVE_PATH FABER_TF_ENVIRONMENTS FABER_CHECKOV_SKIP FABER_SAST FABER_SAST_FAIL_ON_FINDINGS
  export FABER_KUSTOMIZE_VERSION FABER_KUSTOMIZE_BASE_PATH FABER_KUSTOMIZE_LOAD_RESTRICTOR
  export FABER_KUSTOMIZE_SCAN_OVERLAY FABER_KUSTOMIZE_OVERLAYS FABER_KUBE_LINTER_CONFIG FABER_YAMLLINT_PATHS
  export FABER_NODE_FRAMEWORK
  export FABER_CI_EMAIL FABER_CI_NAME FABER_NPM_DEFAULT_SCOPE FABER_ORB_SLUG
  export FABER_HEALTH_PATH FABER_HEALTH_PORT FABER_HEALTH_DB
  export FABER_SONAR FABER_CD
}

# Build the envsubst variable list
get_envsubst_vars() {
  # shellcheck disable=SC2016
  echo '${FABER_PIPELINE} ${FABER_ORB_VERSION} ${FABER_IMAGE_NAME} ${FABER_JAVA_VERSION} ${FABER_NODE_VERSION} ${FABER_SONAR_PROJECT_KEY} ${FABER_DOCKER_REGISTRY} ${FABER_CD_REPO} ${FABER_CD_FORMAT} ${FABER_CD_ENV_DEVELOP} ${FABER_CD_ENV_STAGING} ${FABER_CD_ENV_PROD} ${FABER_CD_ENV_RELEASE} ${FABER_COVERAGE_MIN} ${FABER_E2E} ${FABER_SBOM} ${FABER_CONTEXT_REGISTRY} ${FABER_CONTEXT_GITHUB} ${FABER_CONTEXT_SONAR} ${FABER_CONTEXT_NVD} ${FABER_NPM_AUTH} ${FABER_NPM_SCOPES} ${FABER_SERVICES_JSON} ${FABER_TEST_SETUP_SCRIPT} ${FABER_TEST_COMMANDS_JSON} ${FABER_COVERAGE_TOOL} ${FABER_COVERAGE_COMMAND} ${FABER_GITHUB_RELEASE} ${FABER_SAST} ${FABER_SAST_FAIL_ON_FINDINGS} ${FABER_HEALTH_PATH} ${FABER_HEALTH_PORT} ${FABER_HEALTH_DB} ${FABER_TF_PATH} ${FABER_TF_LIVE_PATH} ${FABER_TF_ENVIRONMENTS} ${FABER_CHECKOV_SKIP} ${FABER_KUSTOMIZE_VERSION} ${FABER_KUSTOMIZE_BASE_PATH} ${FABER_KUSTOMIZE_LOAD_RESTRICTOR} ${FABER_KUSTOMIZE_SCAN_OVERLAY} ${FABER_KUSTOMIZE_OVERLAYS} ${FABER_KUBE_LINTER_CONFIG} ${FABER_YAMLLINT_PATHS} ${FABER_CI_EMAIL} ${FABER_CI_NAME} ${FABER_NPM_DEFAULT_SCOPE} ${FABER_ORB_SLUG}'
}
FABER_EXTRACT_EOF

cat > /tmp/faber/templates/java-webapp.yml.tpl << 'FABER_TPL_EOF'
version: 2.1

orbs:
  faber: ${FABER_ORB_SLUG}@${FABER_ORB_VERSION}

workflows:
  pr-checks:
    jobs:
      - faber/mvn_build_and_test:
          name: build-and-test
          java_version: "${FABER_JAVA_VERSION}"
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - faber/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - faber/sast_scan:
          name: sast-scan
          fail_on_findings: "${FABER_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - faber/mvn_code_quality:
          name: code-quality
          java_version: "${FABER_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - faber/mvn_coverage:
          name: coverage
          java_version: "${FABER_JAVA_VERSION}"
          min_instruction: "${FABER_COVERAGE_MIN}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - faber/security_scan:
          name: security-scan
          java_version: "${FABER_JAVA_VERSION}"
          context:
            - ${FABER_CONTEXT_NVD}
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      ##IF_E2E##
      - faber/mvn_e2e_test:
          name: e2e-tests
          java_version: "${FABER_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      ##ENDIF_E2E##

  ##INCLUDE_DEPLOY java-webapp-deploy develop develop ${FABER_CD_ENV_DEVELOP}##
  ##INCLUDE_DEPLOY java-webapp-deploy staging staging ${FABER_CD_ENV_STAGING}##

  release-candidate:
    jobs:
      - faber/mvn_build_and_test:
          name: build-and-test
          java_version: "${FABER_JAVA_VERSION}"
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      - faber/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /release\/.*/
      - faber/sast_scan:
          name: sast-scan
          fail_on_findings: "${FABER_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only:
                - /release\/.*/
      - faber/mvn_code_quality:
          name: code-quality
          java_version: "${FABER_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      - faber/mvn_coverage:
          name: coverage
          java_version: "${FABER_JAVA_VERSION}"
          min_instruction: "${FABER_COVERAGE_MIN}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      - faber/security_scan:
          name: security-scan
          java_version: "${FABER_JAVA_VERSION}"
          context:
            - ${FABER_CONTEXT_NVD}
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      ##IF_E2E##
      - faber/mvn_e2e_test:
          name: e2e-tests
          java_version: "${FABER_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_E2E##
      ##IF_SONAR##
      - faber/sonar_scan:
          name: sonar-scan
          java_version: "${FABER_JAVA_VERSION}"
          sonar_project_key: ${FABER_SONAR_PROJECT_KEY}
          requires:
            - build-and-test
            - coverage
          context:
            - ${FABER_CONTEXT_SONAR}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_SONAR##
      - faber/docker_build_push:
          name: docker-build-push
          image_name: ${FABER_IMAGE_NAME}
          registry: ${FABER_DOCKER_REGISTRY}
          health_path: ${FABER_HEALTH_PATH}
          health_port: "${FABER_HEALTH_PORT}"
          health_db: "${FABER_HEALTH_DB}"
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_SONAR##
            - sonar-scan
            ##ENDIF_SONAR##
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          context:
            - ${FABER_CONTEXT_REGISTRY}
          filters:
            branches:
              only:
                - /release\/.*/
      ##IF_SBOM##
      - faber/sbom:
          name: sbom
          java_version: "${FABER_JAVA_VERSION}"
          context:
            - ${FABER_CONTEXT_GITHUB}
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_SONAR##
            - sonar-scan
            ##ENDIF_SONAR##
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_SBOM##
      ##IF_CD##
      - faber/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${FABER_CD_REPO}
          environment: ${FABER_CD_ENV_RELEASE}
          cd_format: ${FABER_CD_FORMAT}
          cd_image_name: ${FABER_DOCKER_REGISTRY}/${FABER_IMAGE_NAME}
          ci_git_email: '${FABER_CI_EMAIL}'
          ci_git_name: '${FABER_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_CD##
      ##IF_GITHUB_RELEASE##
      - faber/github_release:
          name: github-release
          requires:
            - docker-build-push
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_GITHUB_RELEASE##

  production:
    jobs:
      - faber/mvn_build_and_test:
          name: build-and-test
          java_version: "${FABER_JAVA_VERSION}"
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      - faber/docker_build_push:
          name: docker-build-push
          image_name: ${FABER_IMAGE_NAME}
          registry: ${FABER_DOCKER_REGISTRY}
          health_path: ${FABER_HEALTH_PATH}
          health_port: "${FABER_HEALTH_PORT}"
          health_db: "${FABER_HEALTH_DB}"
          requires:
            - build-and-test
          context:
            - ${FABER_CONTEXT_REGISTRY}
          filters:
            branches:
              only: main
      ##IF_CD##
      - faber/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${FABER_CD_REPO}
          environment: ${FABER_CD_ENV_PROD}
          cd_format: ${FABER_CD_FORMAT}
          cd_image_name: ${FABER_DOCKER_REGISTRY}/${FABER_IMAGE_NAME}
          ci_git_email: '${FABER_CI_EMAIL}'
          ci_git_name: '${FABER_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      ##ENDIF_CD##
      ##IF_GITHUB_RELEASE##
      - faber/github_release:
          name: github-release
          requires:
            - docker-build-push
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      ##ENDIF_GITHUB_RELEASE##
FABER_TPL_EOF

cat > /tmp/faber/templates/node-api.yml.tpl << 'FABER_TPL_EOF'
version: 2.1

orbs:
  faber: ${FABER_ORB_SLUG}@${FABER_ORB_VERSION}

workflows:
  pr-checks:
    jobs:
      - faber/npm_build_and_test:
          name: build-and-test
          node_version: "${FABER_NODE_VERSION}"
          ##IF_NPM_AUTH##
          npm_auth: true
          npm_scopes: '${FABER_NPM_SCOPES}'
          npm_default_scope: '${FABER_NPM_DEFAULT_SCOPE}'
          ##ENDIF_NPM_AUTH##
          ##IF_SERVICES##
          services: '${FABER_SERVICES_JSON}'
          ##ENDIF_SERVICES##
          ##IF_TEST_SETUP##
          test_setup: ${FABER_TEST_SETUP_SCRIPT}
          ##ENDIF_TEST_SETUP##
          ##IF_CUSTOM_TEST##
          test_commands: '${FABER_TEST_COMMANDS_JSON}'
          ##ENDIF_CUSTOM_TEST##
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - faber/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - faber/sast_scan:
          name: sast-scan
          fail_on_findings: "${FABER_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - faber/npm_code_quality:
          name: code-quality
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - faber/npm_coverage:
          name: coverage
          min_coverage: "${FABER_COVERAGE_MIN}"
          coverage_tool: ${FABER_COVERAGE_TOOL}
          ##IF_COVERAGE_CMD##
          coverage_command: ${FABER_COVERAGE_COMMAND}
          ##ENDIF_COVERAGE_CMD##
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - faber/npm_security_scan:
          name: security-scan
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      ##IF_E2E##
      - faber/npm_e2e_test:
          name: e2e-tests
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      ##ENDIF_E2E##

  ##INCLUDE_DEPLOY node-api-deploy develop develop ${FABER_CD_ENV_DEVELOP}##
  ##INCLUDE_DEPLOY node-api-deploy staging staging ${FABER_CD_ENV_STAGING}##

  release-candidate:
    jobs:
      - faber/npm_build_and_test:
          name: build-and-test
          node_version: "${FABER_NODE_VERSION}"
          ##IF_NPM_AUTH##
          npm_auth: true
          npm_scopes: '${FABER_NPM_SCOPES}'
          npm_default_scope: '${FABER_NPM_DEFAULT_SCOPE}'
          ##ENDIF_NPM_AUTH##
          ##IF_SERVICES##
          services: '${FABER_SERVICES_JSON}'
          ##ENDIF_SERVICES##
          ##IF_TEST_SETUP##
          test_setup: ${FABER_TEST_SETUP_SCRIPT}
          ##ENDIF_TEST_SETUP##
          ##IF_CUSTOM_TEST##
          test_commands: '${FABER_TEST_COMMANDS_JSON}'
          ##ENDIF_CUSTOM_TEST##
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      - faber/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /release\/.*/
      - faber/sast_scan:
          name: sast-scan
          fail_on_findings: "${FABER_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only:
                - /release\/.*/
      - faber/npm_code_quality:
          name: code-quality
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      - faber/npm_coverage:
          name: coverage
          min_coverage: "${FABER_COVERAGE_MIN}"
          coverage_tool: ${FABER_COVERAGE_TOOL}
          ##IF_COVERAGE_CMD##
          coverage_command: ${FABER_COVERAGE_COMMAND}
          ##ENDIF_COVERAGE_CMD##
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      - faber/npm_security_scan:
          name: security-scan
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      ##IF_E2E##
      - faber/npm_e2e_test:
          name: e2e-tests
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_E2E##
      ##IF_SONAR##
      - faber/npm_sonar_scan:
          name: sonar-scan
          node_version: "${FABER_NODE_VERSION}"
          sonar_project_key: ${FABER_SONAR_PROJECT_KEY}
          requires:
            - build-and-test
            - coverage
          context:
            - ${FABER_CONTEXT_SONAR}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_SONAR##
      - faber/docker_build_push:
          name: docker-build-push
          image_name: ${FABER_IMAGE_NAME}
          registry: ${FABER_DOCKER_REGISTRY}
          health_path: ${FABER_HEALTH_PATH}
          health_port: "${FABER_HEALTH_PORT}"
          health_db: "${FABER_HEALTH_DB}"
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          context:
            - ${FABER_CONTEXT_REGISTRY}
          filters:
            branches:
              only:
                - /release\/.*/
      ##IF_SBOM##
      - faber/npm_sbom:
          name: sbom
          node_version: "${FABER_NODE_VERSION}"
          context:
            - ${FABER_CONTEXT_GITHUB}
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_SBOM##
      ##IF_CD##
      - faber/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${FABER_CD_REPO}
          environment: ${FABER_CD_ENV_RELEASE}
          cd_format: ${FABER_CD_FORMAT}
          cd_image_name: ${FABER_DOCKER_REGISTRY}/${FABER_IMAGE_NAME}
          ci_git_email: '${FABER_CI_EMAIL}'
          ci_git_name: '${FABER_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_CD##
      ##IF_GITHUB_RELEASE##
      - faber/github_release:
          name: github-release
          requires:
            - docker-build-push
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_GITHUB_RELEASE##

  production:
    jobs:
      - faber/npm_build_and_test:
          name: build-and-test
          node_version: "${FABER_NODE_VERSION}"
          ##IF_NPM_AUTH##
          npm_auth: true
          npm_scopes: '${FABER_NPM_SCOPES}'
          npm_default_scope: '${FABER_NPM_DEFAULT_SCOPE}'
          ##ENDIF_NPM_AUTH##
          ##IF_SERVICES##
          services: '${FABER_SERVICES_JSON}'
          ##ENDIF_SERVICES##
          ##IF_TEST_SETUP##
          test_setup: ${FABER_TEST_SETUP_SCRIPT}
          ##ENDIF_TEST_SETUP##
          ##IF_CUSTOM_TEST##
          test_commands: '${FABER_TEST_COMMANDS_JSON}'
          ##ENDIF_CUSTOM_TEST##
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      - faber/docker_build_push:
          name: docker-build-push
          image_name: ${FABER_IMAGE_NAME}
          registry: ${FABER_DOCKER_REGISTRY}
          health_path: ${FABER_HEALTH_PATH}
          health_port: "${FABER_HEALTH_PORT}"
          health_db: "${FABER_HEALTH_DB}"
          requires:
            - build-and-test
          context:
            - ${FABER_CONTEXT_REGISTRY}
          filters:
            branches:
              only: main
      ##IF_CD##
      - faber/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${FABER_CD_REPO}
          environment: ${FABER_CD_ENV_PROD}
          cd_format: ${FABER_CD_FORMAT}
          cd_image_name: ${FABER_DOCKER_REGISTRY}/${FABER_IMAGE_NAME}
          ci_git_email: '${FABER_CI_EMAIL}'
          ci_git_name: '${FABER_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      ##ENDIF_CD##
      ##IF_GITHUB_RELEASE##
      - faber/github_release:
          name: github-release
          requires:
            - docker-build-push
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only: main
      ##ENDIF_GITHUB_RELEASE##
FABER_TPL_EOF

cat > /tmp/faber/templates/terraform.yml.tpl << 'FABER_TPL_EOF'
version: 2.1

orbs:
  faber: ${FABER_ORB_SLUG}@${FABER_ORB_VERSION}

workflows:
  pr-checks:
    jobs:
      - faber/validate_repo:
          name: validate-repo
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - faber/tf_validate:
          name: tf-validate
          environments: "${FABER_TF_ENVIRONMENTS}"
          tf_path: ${FABER_TF_PATH}
          base_path: ${FABER_TF_LIVE_PATH}
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - faber/tf_security_scan:
          name: tf-security-scan
          tf_path: ${FABER_TF_PATH}
          checkov_skip: ${FABER_CHECKOV_SKIP}
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - faber/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      ##IF_SAST##
      - faber/sast_scan:
          name: sast-scan
          fail_on_findings: "${FABER_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      ##ENDIF_SAST##

  develop:
    jobs:
      - faber/validate_repo:
          name: validate-repo
          filters:
            branches:
              only: develop
      - faber/tf_validate:
          name: tf-validate
          environments: "${FABER_TF_ENVIRONMENTS}"
          tf_path: ${FABER_TF_PATH}
          base_path: ${FABER_TF_LIVE_PATH}
          filters:
            branches:
              only: develop
      - faber/tf_security_scan:
          name: tf-security-scan
          tf_path: ${FABER_TF_PATH}
          checkov_skip: ${FABER_CHECKOV_SKIP}
          filters:
            branches:
              only: develop
      - faber/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only: develop
      ##IF_SAST##
      - faber/sast_scan:
          name: sast-scan
          fail_on_findings: "${FABER_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only: develop
      ##ENDIF_SAST##

  release-candidate:
    jobs:
      - faber/validate_repo:
          name: validate-repo
          filters:
            branches:
              only:
                - /release\/.*/
      - faber/tf_validate:
          name: tf-validate
          environments: "${FABER_TF_ENVIRONMENTS}"
          tf_path: ${FABER_TF_PATH}
          base_path: ${FABER_TF_LIVE_PATH}
          filters:
            branches:
              only:
                - /release\/.*/
      - faber/tf_security_scan:
          name: tf-security-scan
          tf_path: ${FABER_TF_PATH}
          checkov_skip: ${FABER_CHECKOV_SKIP}
          filters:
            branches:
              only:
                - /release\/.*/
      - faber/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /release\/.*/
      ##IF_SAST##
      - faber/sast_scan:
          name: sast-scan
          fail_on_findings: "${FABER_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only:
                - /release\/.*/
      ##ENDIF_SAST##

  production:
    jobs:
      - faber/validate_repo:
          name: validate-repo
          filters:
            branches:
              only: main
      - faber/tf_validate:
          name: tf-validate
          environments: "${FABER_TF_ENVIRONMENTS}"
          tf_path: ${FABER_TF_PATH}
          base_path: ${FABER_TF_LIVE_PATH}
          filters:
            branches:
              only: main
FABER_TPL_EOF

cat > /tmp/faber/templates/sdk-distribution.yml.tpl << 'FABER_TPL_EOF'
version: 2.1

orbs:
  faber: ${FABER_ORB_SLUG}@${FABER_ORB_VERSION}

workflows:
  pr-validate:
    when:
      not:
        equal: [main, << pipeline.git.branch >>]
    jobs:
      - faber/secrets_scan:
          name: secrets-scan

  release:
    jobs:
      - faber/sdk_release:
          name: sdk-release
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
FABER_TPL_EOF

cat > /tmp/faber/templates/validate-cd-repo.yml.tpl << 'FABER_TPL_EOF'
version: 2.1

orbs:
  faber: ${FABER_ORB_SLUG}@${FABER_ORB_VERSION}

workflows:
  pr-checks:
    jobs:
      - faber/yaml_lint_cd:
          name: yaml-lint
          paths: "${FABER_YAMLLINT_PATHS}"
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - faber/kustomize_validate:
          name: kustomize-validate
          kustomize_version: "${FABER_KUSTOMIZE_VERSION}"
          base_path: "${FABER_KUSTOMIZE_BASE_PATH}"
          overlays: "${FABER_KUSTOMIZE_OVERLAYS}"
          load_restrictor: "${FABER_KUSTOMIZE_LOAD_RESTRICTOR}"
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - faber/kubesec_scan:
          name: kubesec-scan
          scan_overlay: "${FABER_KUSTOMIZE_SCAN_OVERLAY}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - faber/kube_linter:
          name: kube-linter
          scan_overlay: "${FABER_KUSTOMIZE_SCAN_OVERLAY}"
          config: "${FABER_KUBE_LINTER_CONFIG}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/
      - faber/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only:
                - /feature\/.*/
                - /hotfix\/.*/

  develop:
    jobs:
      - faber/yaml_lint_cd:
          name: yaml-lint
          paths: "${FABER_YAMLLINT_PATHS}"
          filters:
            branches:
              only: develop
      - faber/kustomize_validate:
          name: kustomize-validate
          kustomize_version: "${FABER_KUSTOMIZE_VERSION}"
          base_path: "${FABER_KUSTOMIZE_BASE_PATH}"
          overlays: "${FABER_KUSTOMIZE_OVERLAYS}"
          load_restrictor: "${FABER_KUSTOMIZE_LOAD_RESTRICTOR}"
          filters:
            branches:
              only: develop
      - faber/kubesec_scan:
          name: kubesec-scan
          scan_overlay: "${FABER_KUSTOMIZE_SCAN_OVERLAY}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only: develop
      - faber/kube_linter:
          name: kube-linter
          scan_overlay: "${FABER_KUSTOMIZE_SCAN_OVERLAY}"
          config: "${FABER_KUBE_LINTER_CONFIG}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only: develop
      - faber/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only: develop

  release:
    jobs:
      - faber/yaml_lint_cd:
          name: yaml-lint
          paths: "${FABER_YAMLLINT_PATHS}"
          filters:
            branches:
              only: main
      - faber/kustomize_validate:
          name: kustomize-validate
          kustomize_version: "${FABER_KUSTOMIZE_VERSION}"
          base_path: "${FABER_KUSTOMIZE_BASE_PATH}"
          overlays: "${FABER_KUSTOMIZE_OVERLAYS}"
          load_restrictor: "${FABER_KUSTOMIZE_LOAD_RESTRICTOR}"
          filters:
            branches:
              only: main
      - faber/kubesec_scan:
          name: kubesec-scan
          scan_overlay: "${FABER_KUSTOMIZE_SCAN_OVERLAY}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only: main
      - faber/kube_linter:
          name: kube-linter
          scan_overlay: "${FABER_KUSTOMIZE_SCAN_OVERLAY}"
          config: "${FABER_KUBE_LINTER_CONFIG}"
          requires:
            - kustomize-validate
          filters:
            branches:
              only: main
      - faber/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only: main
FABER_TPL_EOF

cat > /tmp/faber/templates/partials/java-webapp-deploy.yml.tpl << 'FABER_PARTIAL_EOF'
  __WORKFLOW_NAME__:
    jobs:
      - faber/mvn_build_and_test:
          name: build-and-test
          java_version: "${FABER_JAVA_VERSION}"
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only: __BRANCH_FILTER__
      - faber/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only: __BRANCH_FILTER__
      - faber/sast_scan:
          name: sast-scan
          fail_on_findings: "${FABER_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only: __BRANCH_FILTER__
      - faber/mvn_code_quality:
          name: code-quality
          java_version: "${FABER_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      - faber/mvn_coverage:
          name: coverage
          java_version: "${FABER_JAVA_VERSION}"
          min_instruction: "${FABER_COVERAGE_MIN}"
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      - faber/security_scan:
          name: security-scan
          java_version: "${FABER_JAVA_VERSION}"
          context:
            - ${FABER_CONTEXT_NVD}
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##IF_E2E##
      - faber/mvn_e2e_test:
          name: e2e-tests
          java_version: "${FABER_JAVA_VERSION}"
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_E2E##
      ##IF_SONAR##
      - faber/sonar_scan:
          name: sonar-scan
          java_version: "${FABER_JAVA_VERSION}"
          sonar_project_key: ${FABER_SONAR_PROJECT_KEY}
          requires:
            - build-and-test
            - coverage
          context:
            - ${FABER_CONTEXT_SONAR}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_SONAR##
      - faber/docker_build_push:
          name: docker-build-push
          image_name: ${FABER_IMAGE_NAME}
          registry: ${FABER_DOCKER_REGISTRY}
          health_path: ${FABER_HEALTH_PATH}
          health_port: "${FABER_HEALTH_PORT}"
          health_db: "${FABER_HEALTH_DB}"
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_SONAR##
            - sonar-scan
            ##ENDIF_SONAR##
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          context:
            - ${FABER_CONTEXT_REGISTRY}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##IF_SBOM##
      - faber/sbom:
          name: sbom
          java_version: "${FABER_JAVA_VERSION}"
          context:
            - ${FABER_CONTEXT_GITHUB}
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_SONAR##
            - sonar-scan
            ##ENDIF_SONAR##
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_SBOM##
      ##IF_CD##
      - faber/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${FABER_CD_REPO}
          environment: __CD_ENVIRONMENT__
          cd_format: ${FABER_CD_FORMAT}
          cd_image_name: ${FABER_DOCKER_REGISTRY}/${FABER_IMAGE_NAME}
          ci_git_email: '${FABER_CI_EMAIL}'
          ci_git_name: '${FABER_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_CD##
FABER_PARTIAL_EOF

cat > /tmp/faber/templates/partials/node-api-deploy.yml.tpl << 'FABER_PARTIAL_EOF'
  __WORKFLOW_NAME__:
    jobs:
      - faber/npm_build_and_test:
          name: build-and-test
          node_version: "${FABER_NODE_VERSION}"
          ##IF_NPM_AUTH##
          npm_auth: true
          npm_scopes: '${FABER_NPM_SCOPES}'
          npm_default_scope: '${FABER_NPM_DEFAULT_SCOPE}'
          ##ENDIF_NPM_AUTH##
          ##IF_SERVICES##
          services: '${FABER_SERVICES_JSON}'
          ##ENDIF_SERVICES##
          ##IF_TEST_SETUP##
          test_setup: ${FABER_TEST_SETUP_SCRIPT}
          ##ENDIF_TEST_SETUP##
          ##IF_CUSTOM_TEST##
          test_commands: '${FABER_TEST_COMMANDS_JSON}'
          ##ENDIF_CUSTOM_TEST##
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only: __BRANCH_FILTER__
      - faber/secrets_scan:
          name: secrets-scan
          filters:
            branches:
              only: __BRANCH_FILTER__
      - faber/sast_scan:
          name: sast-scan
          fail_on_findings: "${FABER_SAST_FAIL_ON_FINDINGS}"
          filters:
            branches:
              only: __BRANCH_FILTER__
      - faber/npm_code_quality:
          name: code-quality
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      - faber/npm_coverage:
          name: coverage
          min_coverage: "${FABER_COVERAGE_MIN}"
          coverage_tool: ${FABER_COVERAGE_TOOL}
          ##IF_COVERAGE_CMD##
          coverage_command: ${FABER_COVERAGE_COMMAND}
          ##ENDIF_COVERAGE_CMD##
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      - faber/npm_security_scan:
          name: security-scan
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##IF_E2E##
      - faber/npm_e2e_test:
          name: e2e-tests
          requires:
            - build-and-test
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_E2E##
      ##IF_SONAR##
      - faber/npm_sonar_scan:
          name: sonar-scan
          node_version: "${FABER_NODE_VERSION}"
          sonar_project_key: ${FABER_SONAR_PROJECT_KEY}
          requires:
            - build-and-test
            - coverage
          context:
            - ${FABER_CONTEXT_SONAR}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_SONAR##
      - faber/docker_build_push:
          name: docker-build-push
          image_name: ${FABER_IMAGE_NAME}
          registry: ${FABER_DOCKER_REGISTRY}
          health_path: ${FABER_HEALTH_PATH}
          health_port: "${FABER_HEALTH_PORT}"
          health_db: "${FABER_HEALTH_DB}"
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          context:
            - ${FABER_CONTEXT_REGISTRY}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##IF_SBOM##
      - faber/npm_sbom:
          name: sbom
          node_version: "${FABER_NODE_VERSION}"
          context:
            - ${FABER_CONTEXT_GITHUB}
          requires:
            - code-quality
            - coverage
            - secrets-scan
            - sast-scan
            - security-scan
            ##IF_E2E##
            - e2e-tests
            ##ENDIF_E2E##
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_SBOM##
      ##IF_CD##
      - faber/update_cd_repo:
          name: update-cd-repo
          cd_repo: ${FABER_CD_REPO}
          environment: __CD_ENVIRONMENT__
          cd_format: ${FABER_CD_FORMAT}
          cd_image_name: ${FABER_DOCKER_REGISTRY}/${FABER_IMAGE_NAME}
          ci_git_email: '${FABER_CI_EMAIL}'
          ci_git_name: '${FABER_CI_NAME}'
          requires:
            - docker-build-push
          context:
            - ${FABER_CONTEXT_GITHUB}
          filters:
            branches:
              only: __BRANCH_FILTER__
      ##ENDIF_CD##
FABER_PARTIAL_EOF

echo "Faber helpers staged to /tmp/faber/"

# ======================================================================
# Main generate_config.sh logic
# ======================================================================

set -euo pipefail

CONFIG_FILE="${FABER_CONFIG:-.faber.yml}"
OUTPUT_FILE="/tmp/generated-config.yml"

# When run via CircleCI << include() >>, BASH_SOURCE is empty.
# Fall back to FABER_SCRIPT_DIR set by the command YAML.
if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
else
  SCRIPT_DIR="${FABER_SCRIPT_DIR:-/tmp/faber}"
fi
TEMPLATE_DIR="${SCRIPT_DIR}/templates"

# Source shared helpers
FABER_HELPERS="${FABER_HELPERS:-${SCRIPT_DIR}/faber_helpers.sh}"
# shellcheck source=faber_helpers.sh
if [[ -f "${FABER_HELPERS}" ]]; then source "${FABER_HELPERS}"
elif ! type faber_header &>/dev/null; then
  faber_header() { echo "=== Faber: ${1:-unknown} ==="; }
  faber_check_tool() { command -v "$1" &>/dev/null || { echo "ERROR: $1 not found"; exit 1; }; }
  faber_download_with_retry() { curl -fsSL --retry 3 "$1" -o "$2"; }
fi

faber_header "generate_config"
faber_check_tool yq --version
faber_check_tool envsubst --version

# Temp file cleanup trap
TEMP_FILES=()
cleanup() {
  for f in "${TEMP_FILES[@]}"; do
    rm -f "${f}" 2>/dev/null || true
  done
}
trap cleanup EXIT

# Source shared variable extraction
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/extract_faber_vars.sh"

# --------------------------------------------------------------------------
# Read .faber.yml
# --------------------------------------------------------------------------
if [[ ! -f "${CONFIG_FILE}" ]]; then
  echo "ERROR: Config file '${CONFIG_FILE}' not found."
  echo "Each repo must have a .faber.yml in the root."
  exit 1
fi

PIPELINE_TYPE=$(yq '.pipeline' "${CONFIG_FILE}")

if [[ -z "${PIPELINE_TYPE}" || "${PIPELINE_TYPE}" == "null" ]]; then
  echo "ERROR: 'pipeline' field is required in ${CONFIG_FILE}."
  exit 1
fi

echo "Pipeline type: ${PIPELINE_TYPE}"

# --------------------------------------------------------------------------
# Validate required fields per pipeline type
# --------------------------------------------------------------------------
validate_required_fields() {
  local pipeline="$1"
  local config="$2"
  local missing=()

  # Global required fields (all pipeline types)
  [[ -z "$(yq '.orb_version // ""' "${config}")" ]] && missing+=("orb_version")

  case "${pipeline}" in
    java-webapp|node-api)
      [[ -z "$(yq '.image_name // ""' "${config}")" ]] && missing+=("image_name")
      [[ -z "$(yq '.docker.registry // ""' "${config}")" ]] && missing+=("docker.registry")
      ;;
    terraform)
      [[ -z "$(yq '.terraform.path // ""' "${config}")" ]] && missing+=("terraform.path")
      ;;
    validate-cd-repo)
      # No additional required fields beyond orb_version
      ;;
  esac

  if [[ ${#missing[@]} -gt 0 ]]; then
    echo "ERROR: Missing required fields for pipeline '${pipeline}':"
    printf '  - %s\n' "${missing[@]}"
    return 1
  fi
}

validate_required_fields "${PIPELINE_TYPE}" "${CONFIG_FILE}"

# --------------------------------------------------------------------------
# Warn about unknown top-level keys (catches typos like java_verion)
# --------------------------------------------------------------------------
KNOWN_KEYS="pipeline orb_version image_name java_version node_version sonar docker cd coverage e2e sbom contexts npm node services test terraform sast health kustomize kube_linter_config"
ACTUAL_KEYS=$(yq 'keys | .[]' "${CONFIG_FILE}" 2>/dev/null || true)
for key in ${ACTUAL_KEYS}; do
  if ! echo "${KNOWN_KEYS}" | grep -qw "${key}"; then
    echo "WARNING: Unknown key '${key}' in ${CONFIG_FILE} (possible typo?)"
  fi
done

# --------------------------------------------------------------------------
# Select template
# --------------------------------------------------------------------------
TEMPLATE_FILE="${TEMPLATE_DIR}/${PIPELINE_TYPE}.yml.tpl"

if [[ ! -f "${TEMPLATE_FILE}" ]]; then
  echo "ERROR: No template found for pipeline type '${PIPELINE_TYPE}'."
  echo "Available templates:"
  find "${TEMPLATE_DIR}" -maxdepth 1 -name '*.yml.tpl' -exec basename {} .yml.tpl \; 2>/dev/null | sed 's/^/  /'
  exit 1
fi

echo "Using template: ${TEMPLATE_FILE}"

# --------------------------------------------------------------------------
# Extract values from .faber.yml and export for envsubst
# --------------------------------------------------------------------------
extract_faber_vars "${CONFIG_FILE}"

# --------------------------------------------------------------------------
# Render template
# --------------------------------------------------------------------------

# Pre-pass: expand ##INCLUDE_DEPLOY <partial> <workflow> <branch> <cd_env>## markers
# Loads partial templates from templates/partials/ and substitutes placeholders
expand_includes() {
  local input="$1"
  local output="$2"
  local partials_dir="${TEMPLATE_DIR}/partials"
  local result
  result=$(mktemp)
  TEMP_FILES+=("${result}")

  cp "${input}" "${result}"

  while IFS= read -r line; do
    if [[ "${line}" =~ ^[[:space:]]*##INCLUDE_DEPLOY[[:space:]]+([^[:space:]]+)[[:space:]]+([^[:space:]]+)[[:space:]]+([^[:space:]]+)[[:space:]]+([^[:space:]]+)##[[:space:]]*$ ]]; then
      local partial="${BASH_REMATCH[1]}"
      local workflow="${BASH_REMATCH[2]}"
      local branch="${BASH_REMATCH[3]}"
      local cd_env="${BASH_REMATCH[4]}"
      local partial_file="${partials_dir}/${partial}.yml.tpl"

      if [[ ! -f "${partial_file}" ]]; then
        echo "ERROR: Partial template '${partial_file}' not found." >&2
        return 1
      fi

      local expanded
      expanded=$(mktemp)
      TEMP_FILES+=("${expanded}")
      sed \
        -e "s/__WORKFLOW_NAME__/${workflow}/g" \
        -e "s/__BRANCH_FILTER__/${branch}/g" \
        -e "s/__CD_ENVIRONMENT__/${cd_env}/g" \
        "${partial_file}" > "${expanded}"

      # Replace the marker line with the expanded partial content
      local swap
      swap=$(mktemp)
      TEMP_FILES+=("${swap}")
      awk -v marker="${line}" -v file="${expanded}" '
        $0 == marker { while ((getline rep < file) > 0) print rep; next }
        { print }
      ' "${result}" > "${swap}"
      cp "${swap}" "${result}"
    fi
  done < "${input}"

  cp "${result}" "${output}"
}

STAGE0_FILE=$(mktemp)
TEMP_FILES+=("${STAGE0_FILE}")
expand_includes "${TEMPLATE_FILE}" "${STAGE0_FILE}"

# Get the list of envsubst variables to replace
ENVSUBST_VARS=$(get_envsubst_vars)

# First pass: envsubst for variable replacement
STAGE1_FILE=$(mktemp)
TEMP_FILES+=("${STAGE1_FILE}")
envsubst "${ENVSUBST_VARS}" < "${STAGE0_FILE}" > "${STAGE1_FILE}"

# Second pass: process conditional blocks
# Removes blocks wrapped in ##IF_<FLAG>## / ##ENDIF_<FLAG>## when flag is false
process_conditionals() {
  local input="$1"
  local output="$2"
  local tmpfile
  tmpfile=$(mktemp)
  TEMP_FILES+=("${tmpfile}")

  cp "${input}" "${tmpfile}"

  # Process each conditional flag
  for flag in E2E SBOM SONAR NPM_AUTH SERVICES TEST_SETUP CUSTOM_TEST COVERAGE_CMD GITHUB_RELEASE SAST CD; do
    local var_name="FABER_${flag}"
    local value="${!var_name:-false}"
    local flag_file
    flag_file=$(mktemp)
    TEMP_FILES+=("${flag_file}")

    if [[ "${value}" == "true" ]]; then
      # Keep the content, strip the markers
      sed "/^[[:space:]]*##IF_${flag}##[[:space:]]*$/d; /^[[:space:]]*##ENDIF_${flag}##[[:space:]]*$/d" "${tmpfile}" > "${flag_file}"
    else
      # Remove everything between markers (inclusive)
      awk "/^[[:space:]]*##IF_${flag}##[[:space:]]*$/{skip=1; next} /^[[:space:]]*##ENDIF_${flag}##[[:space:]]*$/{skip=0; next} !skip" "${tmpfile}" > "${flag_file}"
    fi

    cp "${flag_file}" "${tmpfile}"
  done

  cp "${tmpfile}" "${output}"
}

process_conditionals "${STAGE1_FILE}" "${OUTPUT_FILE}"

# Check for unprocessed conditional markers (indicates typo or unmatched pair)
STALE_MARKERS=$(grep -nE '##(IF|ENDIF)_[A-Z_]+##' "${OUTPUT_FILE}" || true)
if [[ -n "${STALE_MARKERS}" ]]; then
  echo "ERROR: Unprocessed conditional markers found in generated config:"
  echo "${STALE_MARKERS}"
  echo "This usually means a typo in a marker name or an unmatched IF/ENDIF pair."
  exit 1
fi

# Validate the generated YAML
if ! yq '.' "${OUTPUT_FILE}" > /dev/null 2>&1; then
  echo "ERROR: Generated config is not valid YAML"
  echo "Check template and conditional markers for mismatches"
  exit 1
fi

# Validate output file was actually created
if [[ ! -s "${OUTPUT_FILE}" ]]; then
  echo "ERROR: Generated config file is empty or missing at ${OUTPUT_FILE}."
  exit 1
fi

echo "Generated config written to: ${OUTPUT_FILE}"
echo "---"
head -20 "${OUTPUT_FILE}"
echo "..."
echo "($(wc -l < "${OUTPUT_FILE}") total lines)"
