#!/usr/bin/env bash
set -euo pipefail

# Build a self-contained generate_config.sh that embeds all helpers
# and templates. The orb includes this packed version via << include() >>.
#
# Source files remain separate in src/scripts/ for development and testing.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
SRC="${PROJECT_DIR}/src/scripts"
OUT="${SRC}/packed_generate_config.sh"

echo "Packing generate_config.sh..."

{
  echo '#!/usr/bin/env bash'
  echo 'set -euo pipefail'
  echo ''
  echo '# ======================================================================'
  echo '# AUTO-GENERATED by scripts/pack_generate_config.sh'
  echo '# Do not edit directly. Edit src/scripts/*.sh and re-pack.'
  echo '# ======================================================================'
  echo ''
  echo '# Stage helper files to /tmp/faber/ so generate_config.sh can find them'
  echo 'mkdir -p /tmp/faber/templates/partials'
  echo ''

  # Embed faber_helpers.sh
  echo 'cat > /tmp/faber/faber_helpers.sh << '"'"'FABER_HELPERS_EOF'"'"
  cat "${SRC}/faber_helpers.sh"
  echo 'FABER_HELPERS_EOF'
  echo ''

  # Embed extract_faber_vars.sh
  echo 'cat > /tmp/faber/extract_faber_vars.sh << '"'"'FABER_EXTRACT_EOF'"'"
  cat "${SRC}/extract_faber_vars.sh"
  echo 'FABER_EXTRACT_EOF'
  echo ''

  # Embed each template
  for tpl in java-webapp node-api terraform sdk-distribution validate-cd-repo; do
    echo "cat > /tmp/faber/templates/${tpl}.yml.tpl << 'FABER_TPL_EOF'"
    cat "${SRC}/templates/${tpl}.yml.tpl"
    echo 'FABER_TPL_EOF'
    echo ''
  done

  # Embed partials
  for partial in java-webapp-deploy node-api-deploy; do
    echo "cat > /tmp/faber/templates/partials/${partial}.yml.tpl << 'FABER_PARTIAL_EOF'"
    cat "${SRC}/templates/partials/${partial}.yml.tpl"
    echo 'FABER_PARTIAL_EOF'
    echo ''
  done

  echo 'echo "Faber helpers staged to /tmp/faber/"'
  echo ''
  echo '# ======================================================================'
  echo '# Main generate_config.sh logic'
  echo '# ======================================================================'
  echo ''

  # Append the main script, skipping the shebang
  tail -n +2 "${SRC}/generate_config.sh"

} > "${OUT}"

chmod +x "${OUT}"
echo "Packed to: ${OUT}"
echo "Lines: $(wc -l < "${OUT}")"
